# Login in hugginFace

In [1]:
from huggingface_hub import notebook_login

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

# Import data

In [2]:
import pandas as pd

df = pd.read_csv('Dataset/CleannedDataset/newDataframeWithOldCleanedPoliticsVersion.csv')

df = df.reset_index(drop=True)
df

,url,title,text,authors,domain,score,country,language,topics,paywall,opinion_advocacy,label
0,https://nemontananews.com/stories/670532029-1-...,1 gas station in cities throughout Phillips Co...,Federal Energy Regulatory Commission (FERC) Ch...,Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
1,https://nemontananews.com/stories/670175501-mc...,McCone County: Income Maintenance dependency r...,"John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
2,https://nemontananews.com/stories/670489322-da...,"Daniels County residents received $13,488 per ...","John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
3,https://nemontananews.com/stories/670175454-da...,Daniels County: Income Maintenance made up 0.8...,"John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
4,https://nemontananews.com/stories/670413125-wh...,Where could drivers find the cheapest gas in c...,Federal Energy Regulatory Commission (FERC) Co...,Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19471,https://www.truthdig.com/articles/us-house-vot...,US House Vote Rolls Back Wetlands Regulations,The U.S. House voted Thursday to undo a Biden ...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19472,https://www.truthdig.com/articles/environmenta...,Environmental Racism in Canada,Informed nine months after the fact that its h...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19473,https://www.truthdig.com/articles/the-runaway-...,The Runaway Train of Corporate Greed,Thursday’s U.S. Senate hearing about the ongoi...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19474,https://www.truthdig.com/articles/ron-desantis...,Ron DeSantis’ Phantom War Against Voter Fraud,A new Florida law gives Gov.Ron DeSantis’ pros...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19475,https://www.truthdig.com/articles/the-conserva...,The Conservative Teneo Network Is Reshaping Am...,This story was originally published by ProPubl...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3

# BERT

In [3]:
import gc
import torch
import random
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)
from torch.utils.data import DataLoader, TensorDataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from torch.optim import AdamW
from tqdm import tqdm
import os


def bert_cross_validation_with_domain_stratified_split(
    df: pd.DataFrame,
    text_column: str,
    label_column: str,
    domain_column: str,
    output_csv_path: str,
    model_name: str = "bert-base-uncased",
    n_splits: int = 5,
    seed: int = 42,
    epochs: int = 5,
    max_length: int = 256,
    batch_size_train: int = 32,
    batch_size_eval: int = 16,
    learning_rate: float = 2e-5,
):
    """
    Performs k-fold cross-validation with a BERT-based model on a text classification
    task, ensuring that a domain is entirely in either the train or test set for
    each fold, while stratifying based on the most common label per domain.
    """
    # Set random seeds
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    # Map labels to integers
    unique_labels = sorted(df[label_column].unique())
    num_labels = len(unique_labels)
    label_map = {label: i for i, label in enumerate(unique_labels)}
    df[label_column] = df[label_column].map(label_map)
    print(f"Number of unique labels: {num_labels}, Label mapping: {label_map}")

    # Metrics storage
    balanced_accuracy_scores = []
    accuracy_scores = []
    precision_micro_scores, precision_macro_scores, precision_weighted_scores = [], [], []
    recall_micro_scores, recall_macro_scores, recall_weighted_scores = [], [], []
    f1_micro_scores, f1_macro_scores, f1_weighted_scores = [], [], []
    confusions = []

    # Prepare domain-level data for stratified splitting
    grouped = df.groupby(domain_column)
    domains = list(grouped.groups.keys())
    # Use most frequent label in each domain for stratification
    domain_labels = [group[label_column].mode()[0] for _, group in grouped]

    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    folds = []

    # Create folds
    for train_idx, test_idx in skf.split(domains, domain_labels):
        train_domains = [domains[i] for i in train_idx]
        test_domains = [domains[i] for i in test_idx]
        train = df[df[domain_column].isin(train_domains)].reset_index(drop=True)
        test = df[df[domain_column].isin(test_domains)].reset_index(drop=True)
        folds.append((train, test))

    # Process each fold
    for fold_idx, (train, test) in enumerate(folds):
        print(f"\n{'='*40}")
        print(f"Processing BERT Fold {fold_idx+1}/{n_splits}")
        print(f"{'='*40}")

        # Print unique domains
        print(f"Train Domains: {train[domain_column].unique()}")
        print(f"Test Domains: {test[domain_column].unique()}")

        # Print label distribution percentages
        train_dist = train[label_column].value_counts(normalize=True) * 100
        test_dist = test[label_column].value_counts(normalize=True) * 100
        print("Train label distribution (%):")
        print(train_dist)
        print("Test label distribution (%):")
        print(test_dist)

        # Cleanup
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        # Tokenization
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        train_encodings = tokenizer(
            train[text_column].tolist(),
            truncation=True,
            padding="max_length",
            max_length=max_length,
            return_tensors="pt",
        )
        test_encodings = tokenizer(
            test[text_column].tolist(),
            truncation=True,
            padding="max_length",
            max_length=max_length,
            return_tensors="pt",
        )

        # Datasets & Dataloaders
        train_dataset = TensorDataset(
            train_encodings.input_ids,
            train_encodings.attention_mask,
            torch.tensor(train[label_column].tolist())
        )
        test_dataset = TensorDataset(
            test_encodings.input_ids,
            test_encodings.attention_mask,
            torch.tensor(test[label_column].tolist())
        )
        train_loader = DataLoader(train_dataset, batch_size=batch_size_train, shuffle=True)
        test_loader = DataLoader(test_dataset, batch_size=batch_size_eval)

        # Model
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = AutoModelForSequenceClassification.from_pretrained(
            model_name, num_labels=num_labels
        ).to(device)
        optimizer = AdamW(model.parameters(), lr=learning_rate)

        # Training
        for epoch in range(epochs):
            model.train()
            total_loss = 0
            progress_bar = tqdm(train_loader, desc=f"Fold {fold_idx+1} Epoch {epoch+1}/{epochs}")
            for batch in progress_bar:
                input_ids, attention_mask, labels = [b.to(device) for b in batch]
                optimizer.zero_grad()
                outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                loss = outputs.loss
                loss.backward()
                optimizer.step()
                total_loss += loss.item()
                progress_bar.set_postfix({'loss': f"{loss.item():.4f}"})
            print(f"Epoch {epoch+1} avg loss: {total_loss/len(train_loader):.4f}")

        # Evaluation
        model.eval()
        val_preds, val_labels = [], []
        with torch.no_grad():
            for batch in tqdm(test_loader, desc=f"Evaluating Fold {fold_idx+1}"):
                input_ids, attention_mask, labels = batch
                input_ids, attention_mask = input_ids.to(device), attention_mask.to(device)
                outputs = model(input_ids, attention_mask=attention_mask)
                preds = torch.argmax(outputs.logits, dim=1).cpu()
                val_preds.extend(preds.tolist())
                val_labels.extend(labels.tolist())

        # Metrics
        balanced_acc = balanced_accuracy_score(val_labels, val_preds)
        acc = accuracy_score(val_labels, val_preds)
        precision_micro = precision_score(val_labels, val_preds, average="micro")
        precision_macro = precision_score(val_labels, val_preds, average="macro", zero_division=0)
        precision_weighted = precision_score(val_labels, val_preds, average="weighted", zero_division=0)
        recall_micro = recall_score(val_labels, val_preds, average="micro")
        recall_macro = recall_score(val_labels, val_preds, average="macro", zero_division=0)
        recall_weighted = recall_score(val_labels, val_preds, average="weighted", zero_division=0)
        f1_micro = f1_score(val_labels, val_preds, average="micro")
        f1_macro = f1_score(val_labels, val_preds, average="macro", zero_division=0)
        f1_weighted = f1_score(val_labels, val_preds, average="weighted", zero_division=0)
        confusion = confusion_matrix(val_labels, val_preds).tolist()

        # Store metrics
        balanced_accuracy_scores.append(balanced_acc)
        accuracy_scores.append(acc)
        precision_micro_scores.append(precision_micro)
        precision_macro_scores.append(precision_macro)
        precision_weighted_scores.append(precision_weighted)
        recall_micro_scores.append(recall_micro)
        recall_macro_scores.append(recall_macro)
        recall_weighted_scores.append(recall_weighted)
        f1_micro_scores.append(f1_micro)
        f1_macro_scores.append(f1_macro)
        f1_weighted_scores.append(f1_weighted)
        confusions.append(confusion)

        # Save fold results
        fold_results = pd.DataFrame({
            "Fold": [fold_idx + 1],
            "Balanced_Accuracy": [balanced_acc],
            "Accuracy": [acc],
            "Precision_Micro": [precision_micro],
            "Precision_Macro": [precision_macro],
            "Precision_Weighted": [precision_weighted],
            "Recall_Micro": [recall_micro],
            "Recall_Macro": [recall_macro],
            "Recall_Weighted": [recall_weighted],
            "F1_Micro": [f1_micro],
            "F1_Macro": [f1_macro],
            "F1_Weighted": [f1_weighted],
            "Confusion_Matrix": [str(confusion)],
            "True_Labels": [str(val_labels)],
            "Predicted_Labels": [str(val_preds)],
        })


        # Inside your cross-validation loop, after training & evaluation:
        model_save_dir = 'Results/Classification/' + label_column + '/Models'
        os.makedirs(model_save_dir, exist_ok=True)
        
        # Define a unique name for each fold model
        model_save_path = os.path.join(model_save_dir, f"bert_fold_{fold_idx+1}.pt")
        
        # Save model state_dict
        torch.save(model.state_dict(), model_save_path)
        print(f"Fold {fold_idx+1} model saved to {model_save_path}")
        
        # Continue with saving results
        try:
            existing_results = pd.read_csv(output_csv_path)
            fold_results = pd.concat([existing_results, fold_results], ignore_index=True)
        except FileNotFoundError:
            pass
        fold_results.to_csv(output_csv_path, index=False)
        print(f"Fold {fold_idx+1} results saved to {output_csv_path}")
        
        # Cleanup
        del model, optimizer, train_loader, test_loader
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
            
    print('Cross validation done!')

/home/fabio.pinelli/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py:628: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")

In [ ]:
bert_cross_validation_with_domain_stratified_split(
    df=df,
    text_column="text",
    label_column="label",
    output_csv_path="Results/Classification/bert.csv",
    domain_column="domain",
)

Number of unique labels: 5, Label mapping: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}

========================================
Processing BERT Fold 1/5
========================================
Train Domains: ['nemontananews.com' 'theguardiansofdemocracy.com'
 'middlesborodailynews.com' 'tribunemag.co.uk' 'valiantnews.com'
 'realclearinvestigations.com' 'infacts.org' 'patriotsgazette.com'
 'salisburypost.com' 'riverfronttimes.com' 'bluestatebluesnews.com'
 'politico.eu' 'ncindiananews.com' 'anthonyblogan.com'
 'arizonadailyindependent.com' 'aei.org' 'texastribune.org'
 'southtulsatoday.com' 'indystandard.com' 'defenseone.com'
 'eciowanews.com' 'thecoastlandtimes.com' 'southwinstonsalemnews.com'
 'clantonadvertiser.com' 'dcenquirer.com' 'thedcpatriot.com'
 'indo-caribbean.com' 'state-journal.com' 'spiked-online.com'
 'gatewayreporter.com' 'africanvoiceonline.co.uk' 'conservtribune.com'
 'foreignpolicy.com' 'dailysoundandfury.com' 'brewtonstandard.com'
 'taz.de' 'unioncountyreview.com' 'arabnews.com' 'sfbayview.com'
 'theamericanconservative.com' 'ijr.org' 'muslimnews.co.uk'
 'foothillsreview.com' 'coppercourier.com' 'christianpost.com'
 'providencereporter.com' 'tennesseestar.com' 'cbn.com' 'thejc.com'
 'irishcentral.com' 'lobservateur.com' 'nwmontananews.com'
 'conservativeundergroundnews.com' 'townhall.com' '5pillarsuk.com'
 'faithwire.com' 'litchfieldhillstoday.com' 'clarkcountytoday.com'
 'americustimesrecorder.com' 'thepoliticalinsider.com'
 'washingtonmonthly.com' 'unmuzzlednews.com' 'easterneye.biz'
 'illinoispolicy.org' 'pressprogress.ca' 'tuscarawasnews.com'
 'politicalanimalnews.com' 'norcalrecord.com' 'ijr.com' 'nwkansasnews.com'
 'lagrangenews.com' 'reason.com' 'waterfordtoday.com'
 'hartselleenquirer.com' 'floridapolitics.com' 'cfr.org'
 'cordeledispatch.com' 'westlucasnews.com' 'claiborneprogress.net'
 'truthout.org' 'wcminnesotanews.com' 'politicaljournalreview.com'
 'entertainme.whatfinger.com' 'greenvilleadvocate.com' 'ammoland.com'
 'grandrapidsreporter.com' 'projectveritas.com' 'franklincountytimes.com'
 'northcharlottetoday.com' 'georgiastarnews.com' 'oxfordeagle.com'
 'newser.com' 'utopia.de' 'sandhillstoday.com' 'thelily.com'
 'nevalleytimes.com' 'northcolumbusnews.com' 'mikehuckabee.com'
 'brexitnews.tv' 'ourpatriot.com' 'rochesterreporter.com'
 'theohiostar.com' 'deadstate.org' 'northhamptonnews.com'
 'lowndessignal.com' 'swwyomingnews.com' 'reitschuster.de'
 'rightwingwatch.org' 'theguardian.com' 'merrimackvalleynews.com'
 'natchezdemocrat.com' 'northpinellasnews.com' 'keystonenewsroom.com'
 'highline.huffingtonpost.com' 'morrisleader.com' 'dailyleader.com'
 'capitalbnews.org' 'theinteriorjournal.com' 'freebeacon.com'
 'rollcall.com' 'segeorgianews.com' 'swissinfo.ch' 'netarrantnews.com'
 'twitchy.com' 'sowisconsintimes.com' 'newjerseyglobe.com'
 'aroostooknews.com' 'steadfastdaily.com' 'toddstarnes.com'
 'elections.huffingtonpost.com' 'savannahstandard.com'
 'intellectualtakeout.org' 'nachdenkseiten.de' 'picayuneitem.com'
 'koinesune.com' 'alternet.org' 'mrctv.org' 'kyivindependent.com'
 'amnews.com' 'southtidewaternews.com' 'objectivist.co' 'vadogwood.com'
 'thebipartisanpress.com' 'swr3.de' 'pensacolatimes.com' 'thesun.co.uk'
 'patriotfetch.com' 'harlanenterprise.net' 'politicalflare.com'
 'thelondoneconomic.com' 'treasurevalleytimes.com' 'queenseagle.com'
 'frontpagemag.com' 'roanoke-chowannewsherald.com' 'bylinetimes.com'
 'ukdefencejournal.org.uk' 'northessexnews.com' 'prageru.com'
 'politics.co.uk' 'dailysignal.com' 'mercertimes.com' 'elizabethton.com'
 'asiansunday.co.uk' 'southcolumbusnews.com' 'magnoliastatelive.com'
 'hotair.com' 'deneenborelli.com' 'news.sky.com' 'hindstoday.com'
 'justsecurity.org' 'williamsonnews.com' 'redstatewatcher.com'
 'offthepress.com' 'theweek.com' 'thenationaltelegraph.com'
 'projects.huffingtonpost.com' 'nysun.com' 'boisecitywire.com'
 'themichiganstar.com' 'ansamed.info' 'sacorridornews.com'
 'rightnewswire.com' 'panews.com' 'westvolusianews.com'
 'thecharlottegazette.com' 'txrealtynews.com' 'outkick.com'
 'clemmonscourier.net' 'senebraskanews.com' 'drudgereport.com'
 'cistranfinance.com' 'leaderpub.com' 'manilabusinessdaily.com'
 'atmoreadvance.com' 'orlandostandard.com' 'suffolknewsherald.com'
 'utahvalleytimes.com' 'grabien.com' 'seindiananews.com'
 'thepatriotjournal.com' 'justthenews.com' 'swalleghenynews.com'
 'checksandbalancesproject.org' 'mediarightnews.com'
 'northkentuckynews.com' 'rewirenewsgroup.com' 'christianheadlines.com'
 'winchestersun.com' 'southwichitanews.com' 'notthebee.com'
 'jewishpress.com' 'westindynews.com' 'ncncnews.com' 'redstate.com'
 'thepostmillennial.com' 'northrichmondtoday.com' 'andalusiastarnews.com'
 'independentchronicle.com' 'americanlookout.com' 'ourdavie.com'
 'creativedestructionmedia.com' 'respectnh.com' 'democratica.com'
 'demopolistimes.com' 'heartlandsignal.com' 'thenevadaglobe.com'
 'centralcoloradonews.com' 'northbirminghamtimes.com' 'patriotpost.us'
 'decisiondeskhq.com' 'talkingpointsmemo.com' 'swtennnews.com'
 'thewashingtondailynews.com' 'setennnews.com' 'orangeleader.com'
 'northcoastalnews.com' 'gandernewsroom.com' 'sarahpalin.com'
 'southkingnews.com' 'euronews.com' 'valleytimes-news.com' 'ozy.com'
 'jacksonpurchasenews.com' 'prentissheadlight.com' 'patriotjournal.org'
 'jessaminejournal.com' 'metrolexnews.com' 'gopdailybrief.com'
 'newsbusters.org' 'centralfloridapost.com' 'albertleatribune.com'
 'farmvilleherald.com' 'motherjones.com' 'polinews.org' 'observer.com'
 'floridaparishnews.com' 'pantsonfirenews.com' 'dallasobserver.com'
 'lehightimes.com' 'gtrtimes.com' 'amgreatness.com'
 'shelbycountyreporter.com' 'northguilfordnews.com' 'upnorthnewswi.com'
 'bogalusadailynews.com' 'lbc.co.uk' 'sturgiscoldwaternews.com'
 'redrightdaily.com' 'patriotpulse.net' 'ecnorthcarolinanews.com' 'ntd.tv'
 'w-j.co' 'neatlantanews.com' 'thelibertarianrepublic.com'
 'conservativetribune.com' 'southdsmnews.com' 'vicksburgpost.com'
 'yellowhammernews.com' 'northshorelanews.com' 'alabamanow.com'
 'kentcotimes.com' 'libertarianinstitute.org' 'aldianews.com'
 'thesnaponline.com' 'nickadamsusa.com' 'americanpress.com' 'cityam.com'
 'southomahatimes.com' 'theminnesotasun.com' 'renewedright.com'
 'cheddar.com' 'waterlootimes.com' 'easthudvalleynews.com'
 'thewildcard.com' 'imperialcanews.com' 'northhoustonnews.com'
 'ecmissnews.com' 'hudsontoday.com' 'tnc.news' 'topekasun.com'
 'evergreenreporter.com' 'stlouisreporter.com' 'westatlantanews.com'
 'readfrontier.org' 'olddominionnews.com' 'educationdailywire.com'
 'emeraldcoasttimes.com' 'thecanary.co' 'lifezette.com'
 'westernjournal.com' 'kokomostandard.com' 'southtrianglenews.com'
 'dailypatriotreport.com' 'mic.com' 'swriversidenews.com'
 'southatlantanews.com' 'nationalinterest.org' 'lubbocktimes.com'
 'westsgvnews.com' 'data.huffingtonpost.com' 'westlatimes.com'
 'intpolicydigest.org' 'southsidevanews.com' 'centralmissourinews.com'
 'neohiotimes.com' 'fee.org' 'southsoundtimes.com' 'stjoebentonharbor.com'
 'cnnespanol.cnn.com' 'lewistontimes.com' 'jeffcitynews.com'
 'currentaffairs.org' 'rocklandreporter.com' 'euromaidanpress.com'
 'asianimage.co.uk' 'luzernetimes.com' 'thefulcrum.us' 'ndnorthnews.com'
 'searizonanews.com' 'huffpost.com' 'english.alaraby.co.uk'
 'southsfbaynews.com' 'sandovalnews.com' 'eaglevalleytimes.com'
 'americanprogress.org' 'bizpacreview.com' 'news-front.info'
 'flagandcross.com' 'politicshome.com' 'realrawnews.com' 'truthdig.com']
Test Domains: ['ecoklahomanews.com' 'westhamiltonnews.com' 'themadisonrecord.com'
 'nationalmemo.com' 'ntd.com' 'swmontanatimes.com' 'larimernews.com'
 'thecountersignal.com' 'pravda.com.ua' 'hongkongfp.com'
 'americanwirenews.com' 'armaghi.com' 'editorial.huffingtonpost.com'
 'northinlandnews.com' 'middleeasteye.net' 'counterpunch.org'
 'linkiesta.it' 'msmagazine.com' 'freespeech.org' 'theblaze.com'
 'foramerica.org' 'theroot.com' 'thepostsearchlight.com'
 'kenbridgevictoriadispatch.com' 'desantisdaily.com' 'policetribune.com'
 'shondaland.com' 'msnbc.com' 'patriotpost.com' 'rabble.ca'
 'spotlightpa.org' 'cornishstuff.com' 'theamericanonews.com'
 'labourlist.org' 'troymessenger.com' 'huffingtonpost.com' 'rowannews.com'
 'southbrowardnews.com' 'aapsonline.org' 'centennialstatenews.com'
 'cardinalpine.com' 'thefirsttv.com' 'jta.org' 'nigerianwatch.com'
 'centrallouisiananews.com' 'smithfieldtimes.com' 'dailyboulder.com'
 'treasurecoastsun.com' 'conservativewoman.co.uk' 'westernjournalism.com'
 'disrn.com' 'eastindynews.com' 'analyzingamerica.org'
 'mustreadalaska.com' 'judicialwatch.org' 'irontontribune.com'
 'selmatimesjournal.com' 'tryondailybulletin.com' 'endtimeheadlines.org'
 'southknoxnews.com' 'weststarknews.com' 'angolabusinessdaily.com'
 'projectveritasaction.com' 'eastmichigannews.com' 'dailywire.com'
 'legalinsurrection.com' 'southcotimes.com' 'deeside.com' 'neonnettle.com'
 'muskegonsun.com' 'cobbreporter.com' 'cantonreporter.com'
 'live.huffingtonpost.com' 'henricotimes.com' 'algemeiner.com'
 'greenvillereporter.com' 'patientdaily.com' 'meduza.io' 'dallasvoice.com'
 'northfairfaxnews.com' 'southlouisiananews.com' 'gbnews.uk'
 'fayettevilletoday.com' 'thenewcivilrightsmovement.com' 'knoxtimes.com'
 'petroplexnews.com' 'aclu.org' 'thegrayzone.com']
Train label distribution (%):
label
0    25.377062
3    25.210192
2    24.780181
1    14.248123
4    10.384443
Name: proportion, dtype: float64
Test label distribution (%):
label
3    28.575096
0    23.543004
1    20.436457
2    19.486521
4     7.958922
Name: proportion, dtype: float64

2025-11-11 09:26:00.227767: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-11 09:26:00.387034: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1762853160.450388  398525 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1762853160.469710  398525 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1762853160.593377  398525 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1762853160.593403  398525 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1762853160.593409  398525 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1762853160.593413  398525 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-11-11 09:26:00.608615: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fold 1 Epoch 1/5:   0%|                                 | 0/487 [00:00<?, ?it/s]/home/fabio.pinelli/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py:1520: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Fold 1 Epoch 1/5: 100%|██████████| 487/487 [03:31<00:00,  2.30it/s, loss=0.9726]

Epoch 1 avg loss: 0.8655

Fold 1 Epoch 2/5: 100%|██████████| 487/487 [03:27<00:00,  2.34it/s, loss=0.3171]

Epoch 2 avg loss: 0.5281

Fold 1 Epoch 3/5: 100%|██████████| 487/487 [03:26<00:00,  2.36it/s, loss=0.3764]

Epoch 3 avg loss: 0.3411

Fold 1 Epoch 4/5: 100%|██████████| 487/487 [03:26<00:00,  2.36it/s, loss=0.2660]

Epoch 4 avg loss: 0.2090

Fold 1 Epoch 5/5: 100%|██████████| 487/487 [03:26<00:00,  2.36it/s, loss=0.1865]

Epoch 5 avg loss: 0.1219

Evaluating Fold 1: 100%|██████████████████████| 244/244 [00:16<00:00, 14.73it/s]

Fold 1 model saved to Results/Classification/label/Models/bert_fold_1.pt
Fold 1 results saved to Results/Classification/bert.csv

========================================
Processing BERT Fold 2/5
========================================
Train Domains: ['nemontananews.com' 'theguardiansofdemocracy.com'
 'middlesborodailynews.com' 'tribunemag.co.uk' 'ecoklahomanews.com'
 'valiantnews.com' 'realclearinvestigations.com' 'westhamiltonnews.com'
 'riverfronttimes.com' 'bluestatebluesnews.com' 'themadisonrecord.com'
 'politico.eu' 'ncindiananews.com' 'anthonyblogan.com'
 'arizonadailyindependent.com' 'texastribune.org' 'southtulsatoday.com'
 'nationalmemo.com' 'indystandard.com' 'defenseone.com' 'eciowanews.com'
 'thecoastlandtimes.com' 'southwinstonsalemnews.com'
 'clantonadvertiser.com' 'dcenquirer.com' 'thedcpatriot.com'
 'spiked-online.com' 'gatewayreporter.com' 'ntd.com'
 'africanvoiceonline.co.uk' 'conservtribune.com' 'foreignpolicy.com'
 'dailysoundandfury.com' 'brewtonstandard.com' 'taz.de'
 'unioncountyreview.com' 'arabnews.com' 'sfbayview.com'
 'swmontanatimes.com' 'theamericanconservative.com' 'ijr.org'
 'muslimnews.co.uk' 'foothillsreview.com' 'coppercourier.com'
 'tennesseestar.com' 'cbn.com' 'thejc.com' 'irishcentral.com'
 'lobservateur.com' 'nwmontananews.com' 'conservativeundergroundnews.com'
 'townhall.com' '5pillarsuk.com' 'larimernews.com' 'clarkcountytoday.com'
 'americustimesrecorder.com' 'thepoliticalinsider.com'
 'washingtonmonthly.com' 'thecountersignal.com' 'unmuzzlednews.com'
 'easterneye.biz' 'pravda.com.ua' 'hongkongfp.com' 'americanwirenews.com'
 'illinoispolicy.org' 'pressprogress.ca' 'politicalanimalnews.com'
 'armaghi.com' 'ijr.com' 'nwkansasnews.com' 'lagrangenews.com'
 'editorial.huffingtonpost.com' 'waterfordtoday.com' 'floridapolitics.com'
 'cfr.org' 'northinlandnews.com' 'cordeledispatch.com' 'middleeasteye.net'
 'westlucasnews.com' 'claiborneprogress.net' 'counterpunch.org'
 'wcminnesotanews.com' 'ammoland.com' 'franklincountytimes.com'
 'northcharlottetoday.com' 'georgiastarnews.com' 'oxfordeagle.com'
 'newser.com' 'utopia.de' 'sandhillstoday.com' 'linkiesta.it'
 'msmagazine.com' 'nevalleytimes.com' 'freespeech.org'
 'northcolumbusnews.com' 'theblaze.com' 'brexitnews.tv' 'foramerica.org'
 'theroot.com' 'thepostsearchlight.com' 'rochesterreporter.com'
 'kenbridgevictoriadispatch.com' 'northhamptonnews.com'
 'lowndessignal.com' 'swwyomingnews.com' 'reitschuster.de'
 'rightwingwatch.org' 'theguardian.com' 'merrimackvalleynews.com'
 'desantisdaily.com' 'natchezdemocrat.com' 'policetribune.com'
 'northpinellasnews.com' 'keystonenewsroom.com' 'shondaland.com'
 'highline.huffingtonpost.com' 'morrisleader.com' 'msnbc.com'
 'dailyleader.com' 'capitalbnews.org' 'patriotpost.com'
 'theinteriorjournal.com' 'freebeacon.com' 'swissinfo.ch'
 'netarrantnews.com' 'twitchy.com' 'rabble.ca' 'steadfastdaily.com'
 'toddstarnes.com' 'elections.huffingtonpost.com' 'spotlightpa.org'
 'intellectualtakeout.org' 'nachdenkseiten.de' 'picayuneitem.com'
 'koinesune.com' 'alternet.org' 'mrctv.org' 'kyivindependent.com'
 'cornishstuff.com' 'theamericanonews.com' 'amnews.com' 'labourlist.org'
 'southtidewaternews.com' 'objectivist.co' 'troymessenger.com'
 'huffingtonpost.com' 'rowannews.com' 'vadogwood.com'
 'thebipartisanpress.com' 'swr3.de' 'southbrowardnews.com'
 'patriotfetch.com' 'harlanenterprise.net' 'aapsonline.org'
 'politicalflare.com' 'thelondoneconomic.com' 'centennialstatenews.com'
 'cardinalpine.com' 'thefirsttv.com' 'treasurevalleytimes.com'
 'roanoke-chowannewsherald.com' 'bylinetimes.com' 'northessexnews.com'
 'prageru.com' 'dailysignal.com' 'elizabethton.com' 'asiansunday.co.uk'
 'jta.org' 'southcolumbusnews.com' 'nigerianwatch.com'
 'magnoliastatelive.com' 'centrallouisiananews.com' 'deneenborelli.com'
 'news.sky.com' 'hindstoday.com' 'smithfieldtimes.com'
 'williamsonnews.com' 'dailyboulder.com' 'redstatewatcher.com'
 'offthepress.com' 'theweek.com' 'thenationaltelegraph.com'
 'projects.huffingtonpost.com' 'nysun.com' 'themichiganstar.com'
 'thecharlottegazette.com' 'txrealtynews.com' 'outkick.com'
 'treasurecoastsun.com' 'clemmonscourier.net' 'senebraskanews.com'
 'conservativewoman.co.uk' 'drudgereport.com' 'westernjournalism.com'
 'disrn.com' 'manilabusinessdaily.com' 'atmoreadvance.com'
 'orlandostandard.com' 'utahvalleytimes.com' 'grabien.com'
 'seindiananews.com' 'justthenews.com' 'swalleghenynews.com'
 'mediarightnews.com' 'rewirenewsgroup.com' 'eastindynews.com'
 'christianheadlines.com' 'analyzingamerica.org' 'southwichitanews.com'
 'mustreadalaska.com' 'notthebee.com' 'jewishpress.com' 'westindynews.com'
 'judicialwatch.org' 'ncncnews.com' 'irontontribune.com'
 'northrichmondtoday.com' 'andalusiastarnews.com'
 'independentchronicle.com' 'creativedestructionmedia.com' 'respectnh.com'
 'selmatimesjournal.com' 'demopolistimes.com' 'tryondailybulletin.com'
 'heartlandsignal.com' 'centralcoloradonews.com' 'endtimeheadlines.org'
 'northbirminghamtimes.com' 'patriotpost.us' 'decisiondeskhq.com'
 'setennnews.com' 'orangeleader.com' 'northcoastalnews.com'
 'gandernewsroom.com' 'southkingnews.com' 'southknoxnews.com'
 'euronews.com' 'valleytimes-news.com' 'ozy.com' 'jacksonpurchasenews.com'
 'prentissheadlight.com' 'patriotjournal.org' 'jessaminejournal.com'
 'newsbusters.org' 'weststarknews.com' 'centralfloridapost.com'
 'angolabusinessdaily.com' 'projectveritasaction.com'
 'farmvilleherald.com' 'motherjones.com' 'eastmichigannews.com'
 'dailywire.com' 'observer.com' 'floridaparishnews.com'
 'pantsonfirenews.com' 'legalinsurrection.com' 'dallasobserver.com'
 'gtrtimes.com' 'amgreatness.com' 'shelbycountyreporter.com'
 'northguilfordnews.com' 'upnorthnewswi.com' 'bogalusadailynews.com'
 'sturgiscoldwaternews.com' 'southcotimes.com' 'patriotpulse.net' 'ntd.tv'
 'w-j.co' 'neatlantanews.com' 'thelibertarianrepublic.com'
 'southdsmnews.com' 'vicksburgpost.com' 'yellowhammernews.com'
 'northshorelanews.com' 'kentcotimes.com' 'libertarianinstitute.org'
 'deeside.com' 'thesnaponline.com' 'americanpress.com' 'cityam.com'
 'southomahatimes.com' 'neonnettle.com' 'muskegonsun.com'
 'theminnesotasun.com' 'cobbreporter.com' 'renewedright.com' 'cheddar.com'
 'waterlootimes.com' 'cantonreporter.com' 'live.huffingtonpost.com'
 'henricotimes.com' 'algemeiner.com' 'easthudvalleynews.com'
 'greenvillereporter.com' 'patientdaily.com' 'meduza.io'
 'northhoustonnews.com' 'ecmissnews.com' 'dallasvoice.com'
 'hudsontoday.com' 'tnc.news' 'topekasun.com' 'evergreenreporter.com'
 'westatlantanews.com' 'readfrontier.org' 'northfairfaxnews.com'
 'educationdailywire.com' 'thecanary.co' 'lifezette.com'
 'westernjournal.com' 'kokomostandard.com' 'mic.com' 'swriversidenews.com'
 'southatlantanews.com' 'nationalinterest.org' 'lubbocktimes.com'
 'southlouisiananews.com' 'westlatimes.com' 'southsidevanews.com'
 'centralmissourinews.com' 'neohiotimes.com' 'southsoundtimes.com'
 'gbnews.uk' 'stjoebentonharbor.com' 'cnnespanol.cnn.com'
 'lewistontimes.com' 'jeffcitynews.com' 'currentaffairs.org'
 'rocklandreporter.com' 'fayettevilletoday.com' 'asianimage.co.uk'
 'luzernetimes.com' 'thenewcivilrightsmovement.com' 'thefulcrum.us'
 'ndnorthnews.com' 'searizonanews.com' 'huffpost.com' 'knoxtimes.com'
 'english.alaraby.co.uk' 'sandovalnews.com' 'eaglevalleytimes.com'
 'petroplexnews.com' 'aclu.org' 'americanprogress.org' 'bizpacreview.com'
 'news-front.info' 'flagandcross.com' 'politicshome.com' 'realrawnews.com'
 'thegrayzone.com' 'truthdig.com']
Test Domains: ['infacts.org' 'patriotsgazette.com' 'salisburypost.com' 'aei.org'
 'indo-caribbean.com' 'state-journal.com' 'christianpost.com'
 'providencereporter.com' 'faithwire.com' 'litchfieldhillstoday.com'
 'tuscarawasnews.com' 'norcalrecord.com' 'reason.com'
 'hartselleenquirer.com' 'truthout.org' 'politicaljournalreview.com'
 'entertainme.whatfinger.com' 'greenvilleadvocate.com'
 'grandrapidsreporter.com' 'projectveritas.com' 'thelily.com'
 'mikehuckabee.com' 'ourpatriot.com' 'theohiostar.com' 'deadstate.org'
 'rollcall.com' 'segeorgianews.com' 'sowisconsintimes.com'
 'newjerseyglobe.com' 'aroostooknews.com' 'savannahstandard.com'
 'pensacolatimes.com' 'thesun.co.uk' 'queenseagle.com' 'frontpagemag.com'
 'ukdefencejournal.org.uk' 'politics.co.uk' 'mercertimes.com' 'hotair.com'
 'justsecurity.org' 'boisecitywire.com' 'ansamed.info'
 'sacorridornews.com' 'rightnewswire.com' 'panews.com'
 'westvolusianews.com' 'cistranfinance.com' 'leaderpub.com'
 'suffolknewsherald.com' 'thepatriotjournal.com'
 'checksandbalancesproject.org' 'northkentuckynews.com'
 'winchestersun.com' 'redstate.com' 'thepostmillennial.com'
 'americanlookout.com' 'ourdavie.com' 'democratica.com'
 'thenevadaglobe.com' 'talkingpointsmemo.com' 'swtennnews.com'
 'thewashingtondailynews.com' 'sarahpalin.com' 'metrolexnews.com'
 'gopdailybrief.com' 'albertleatribune.com' 'polinews.org'
 'lehightimes.com' 'lbc.co.uk' 'redrightdaily.com'
 'ecnorthcarolinanews.com' 'conservativetribune.com' 'alabamanow.com'
 'aldianews.com' 'nickadamsusa.com' 'thewildcard.com' 'imperialcanews.com'
 'stlouisreporter.com' 'olddominionnews.com' 'emeraldcoasttimes.com'
 'southtrianglenews.com' 'dailypatriotreport.com' 'westsgvnews.com'
 'data.huffingtonpost.com' 'intpolicydigest.org' 'fee.org'
 'euromaidanpress.com' 'southsfbaynews.com']
Train label distribution (%):
label
3    26.586299
0    25.173375
2    22.412340
1    15.658824
4    10.169162
Name: proportion, dtype: float64
Test label distribution (%):
label
2    28.712627
0    24.388436
3    23.202372
1    14.825797
4     8.870768
Name: proportion, dtype: float64

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fold 2 Epoch 1/5:   0%|                                 | 0/483 [00:00<?, ?it/s]/home/fabio.pinelli/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py:1520: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Fold 2 Epoch 1/5: 100%|██████████| 483/483 [03:24<00:00,  2.36it/s, loss=0.2248]

Epoch 1 avg loss: 0.8802

Fold 2 Epoch 2/5: 100%|██████████| 483/483 [03:24<00:00,  2.36it/s, loss=1.4619]

Epoch 2 avg loss: 0.5173

Fold 2 Epoch 3/5: 100%|██████████| 483/483 [03:25<00:00,  2.36it/s, loss=0.0582]

Epoch 3 avg loss: 0.3330

Fold 2 Epoch 4/5: 100%|██████████| 483/483 [03:24<00:00,  2.36it/s, loss=0.7752]

Epoch 4 avg loss: 0.2032

Fold 2 Epoch 5/5: 100%|██████████| 483/483 [03:24<00:00,  2.36it/s, loss=0.0044]

Epoch 5 avg loss: 0.1122

Evaluating Fold 2: 100%|██████████████████████| 253/253 [00:17<00:00, 14.67it/s]

Fold 2 model saved to Results/Classification/label/Models/bert_fold_2.pt
Fold 2 results saved to Results/Classification/bert.csv

========================================
Processing BERT Fold 3/5
========================================
Train Domains: ['nemontananews.com' 'theguardiansofdemocracy.com'
 'middlesborodailynews.com' 'tribunemag.co.uk' 'ecoklahomanews.com'
 'valiantnews.com' 'realclearinvestigations.com' 'infacts.org'
 'westhamiltonnews.com' 'patriotsgazette.com' 'salisburypost.com'
 'riverfronttimes.com' 'bluestatebluesnews.com' 'themadisonrecord.com'
 'anthonyblogan.com' 'arizonadailyindependent.com' 'aei.org'
 'southtulsatoday.com' 'nationalmemo.com' 'indystandard.com'
 'defenseone.com' 'thecoastlandtimes.com' 'southwinstonsalemnews.com'
 'clantonadvertiser.com' 'indo-caribbean.com' 'state-journal.com'
 'gatewayreporter.com' 'ntd.com' 'africanvoiceonline.co.uk'
 'conservtribune.com' 'foreignpolicy.com' 'dailysoundandfury.com'
 'brewtonstandard.com' 'taz.de' 'arabnews.com' 'sfbayview.com'
 'swmontanatimes.com' 'theamericanconservative.com' 'ijr.org'
 'foothillsreview.com' 'coppercourier.com' 'christianpost.com'
 'providencereporter.com' 'cbn.com' 'thejc.com' 'irishcentral.com'
 'lobservateur.com' 'nwmontananews.com' 'conservativeundergroundnews.com'
 '5pillarsuk.com' 'larimernews.com' 'faithwire.com'
 'litchfieldhillstoday.com' 'clarkcountytoday.com'
 'americustimesrecorder.com' 'washingtonmonthly.com'
 'thecountersignal.com' 'pravda.com.ua' 'hongkongfp.com'
 'americanwirenews.com' 'illinoispolicy.org' 'tuscarawasnews.com'
 'politicalanimalnews.com' 'norcalrecord.com' 'armaghi.com' 'ijr.com'
 'lagrangenews.com' 'editorial.huffingtonpost.com' 'reason.com'
 'hartselleenquirer.com' 'cfr.org' 'northinlandnews.com'
 'middleeasteye.net' 'claiborneprogress.net' 'truthout.org'
 'counterpunch.org' 'wcminnesotanews.com' 'politicaljournalreview.com'
 'entertainme.whatfinger.com' 'greenvilleadvocate.com' 'ammoland.com'
 'grandrapidsreporter.com' 'projectveritas.com' 'franklincountytimes.com'
 'northcharlottetoday.com' 'georgiastarnews.com' 'oxfordeagle.com'
 'newser.com' 'sandhillstoday.com' 'linkiesta.it' 'msmagazine.com'
 'thelily.com' 'freespeech.org' 'mikehuckabee.com' 'theblaze.com'
 'brexitnews.tv' 'foramerica.org' 'theroot.com' 'ourpatriot.com'
 'thepostsearchlight.com' 'rochesterreporter.com' 'theohiostar.com'
 'kenbridgevictoriadispatch.com' 'deadstate.org' 'northhamptonnews.com'
 'lowndessignal.com' 'swwyomingnews.com' 'reitschuster.de'
 'desantisdaily.com' 'policetribune.com' 'northpinellasnews.com'
 'shondaland.com' 'morrisleader.com' 'msnbc.com' 'dailyleader.com'
 'patriotpost.com' 'theinteriorjournal.com' 'rollcall.com'
 'segeorgianews.com' 'swissinfo.ch' 'netarrantnews.com' 'rabble.ca'
 'sowisconsintimes.com' 'newjerseyglobe.com' 'aroostooknews.com'
 'steadfastdaily.com' 'elections.huffingtonpost.com' 'spotlightpa.org'
 'savannahstandard.com' 'nachdenkseiten.de' 'picayuneitem.com'
 'alternet.org' 'mrctv.org' 'cornishstuff.com' 'theamericanonews.com'
 'labourlist.org' 'southtidewaternews.com' 'objectivist.co'
 'troymessenger.com' 'huffingtonpost.com' 'rowannews.com' 'vadogwood.com'
 'thebipartisanpress.com' 'swr3.de' 'pensacolatimes.com' 'thesun.co.uk'
 'southbrowardnews.com' 'aapsonline.org' 'politicalflare.com'
 'thelondoneconomic.com' 'centennialstatenews.com' 'cardinalpine.com'
 'thefirsttv.com' 'treasurevalleytimes.com' 'queenseagle.com'
 'frontpagemag.com' 'bylinetimes.com' 'ukdefencejournal.org.uk'
 'prageru.com' 'politics.co.uk' 'dailysignal.com' 'mercertimes.com'
 'asiansunday.co.uk' 'jta.org' 'southcolumbusnews.com' 'nigerianwatch.com'
 'hotair.com' 'centrallouisiananews.com' 'news.sky.com' 'hindstoday.com'
 'smithfieldtimes.com' 'justsecurity.org' 'williamsonnews.com'
 'dailyboulder.com' 'redstatewatcher.com' 'projects.huffingtonpost.com'
 'nysun.com' 'boisecitywire.com' 'themichiganstar.com' 'ansamed.info'
 'sacorridornews.com' 'rightnewswire.com' 'panews.com'
 'westvolusianews.com' 'txrealtynews.com' 'treasurecoastsun.com'
 'clemmonscourier.net' 'senebraskanews.com' 'conservativewoman.co.uk'
 'westernjournalism.com' 'cistranfinance.com' 'disrn.com' 'leaderpub.com'
 'atmoreadvance.com' 'orlandostandard.com' 'suffolknewsherald.com'
 'utahvalleytimes.com' 'grabien.com' 'seindiananews.com'
 'thepatriotjournal.com' 'justthenews.com' 'checksandbalancesproject.org'
 'mediarightnews.com' 'northkentuckynews.com' 'rewirenewsgroup.com'
 'eastindynews.com' 'winchestersun.com' 'analyzingamerica.org'
 'mustreadalaska.com' 'notthebee.com' 'jewishpress.com'
 'judicialwatch.org' 'redstate.com' 'irontontribune.com'
 'thepostmillennial.com' 'northrichmondtoday.com'
 'independentchronicle.com' 'americanlookout.com' 'ourdavie.com'
 'creativedestructionmedia.com' 'respectnh.com' 'selmatimesjournal.com'
 'democratica.com' 'demopolistimes.com' 'tryondailybulletin.com'
 'heartlandsignal.com' 'thenevadaglobe.com' 'centralcoloradonews.com'
 'endtimeheadlines.org' 'northbirminghamtimes.com' 'patriotpost.us'
 'decisiondeskhq.com' 'talkingpointsmemo.com' 'swtennnews.com'
 'thewashingtondailynews.com' 'orangeleader.com' 'northcoastalnews.com'
 'sarahpalin.com' 'southkingnews.com' 'southknoxnews.com' 'euronews.com'
 'prentissheadlight.com' 'jessaminejournal.com' 'metrolexnews.com'
 'gopdailybrief.com' 'newsbusters.org' 'weststarknews.com'
 'albertleatribune.com' 'angolabusinessdaily.com'
 'projectveritasaction.com' 'farmvilleherald.com' 'motherjones.com'
 'eastmichigannews.com' 'polinews.org' 'dailywire.com'
 'pantsonfirenews.com' 'legalinsurrection.com' 'dallasobserver.com'
 'lehightimes.com' 'amgreatness.com' 'shelbycountyreporter.com'
 'northguilfordnews.com' 'upnorthnewswi.com' 'bogalusadailynews.com'
 'lbc.co.uk' 'sturgiscoldwaternews.com' 'redrightdaily.com'
 'southcotimes.com' 'patriotpulse.net' 'ecnorthcarolinanews.com' 'ntd.tv'
 'w-j.co' 'neatlantanews.com' 'conservativetribune.com'
 'northshorelanews.com' 'alabamanow.com' 'kentcotimes.com' 'aldianews.com'
 'deeside.com' 'nickadamsusa.com' 'americanpress.com' 'cityam.com'
 'neonnettle.com' 'muskegonsun.com' 'cobbreporter.com' 'renewedright.com'
 'cheddar.com' 'waterlootimes.com' 'cantonreporter.com'
 'live.huffingtonpost.com' 'henricotimes.com' 'algemeiner.com'
 'easthudvalleynews.com' 'thewildcard.com' 'greenvillereporter.com'
 'patientdaily.com' 'meduza.io' 'imperialcanews.com' 'ecmissnews.com'
 'dallasvoice.com' 'hudsontoday.com' 'tnc.news' 'topekasun.com'
 'evergreenreporter.com' 'stlouisreporter.com' 'olddominionnews.com'
 'northfairfaxnews.com' 'educationdailywire.com' 'emeraldcoasttimes.com'
 'thecanary.co' 'lifezette.com' 'westernjournal.com'
 'southtrianglenews.com' 'dailypatriotreport.com' 'swriversidenews.com'
 'southatlantanews.com' 'lubbocktimes.com' 'westsgvnews.com'
 'southlouisiananews.com' 'data.huffingtonpost.com' 'intpolicydigest.org'
 'southsidevanews.com' 'centralmissourinews.com' 'fee.org'
 'southsoundtimes.com' 'gbnews.uk' 'stjoebentonharbor.com'
 'cnnespanol.cnn.com' 'lewistontimes.com' 'jeffcitynews.com'
 'currentaffairs.org' 'rocklandreporter.com' 'euromaidanpress.com'
 'fayettevilletoday.com' 'asianimage.co.uk' 'luzernetimes.com'
 'thenewcivilrightsmovement.com' 'thefulcrum.us' 'ndnorthnews.com'
 'knoxtimes.com' 'southsfbaynews.com' 'sandovalnews.com'
 'petroplexnews.com' 'aclu.org' 'americanprogress.org' 'bizpacreview.com'
 'news-front.info' 'politicshome.com' 'realrawnews.com' 'thegrayzone.com'
 'truthdig.com']
Test Domains: ['politico.eu' 'ncindiananews.com' 'texastribune.org' 'eciowanews.com'
 'dcenquirer.com' 'thedcpatriot.com' 'spiked-online.com'
 'unioncountyreview.com' 'muslimnews.co.uk' 'tennesseestar.com'
 'townhall.com' 'thepoliticalinsider.com' 'unmuzzlednews.com'
 'easterneye.biz' 'pressprogress.ca' 'nwkansasnews.com'
 'waterfordtoday.com' 'floridapolitics.com' 'cordeledispatch.com'
 'westlucasnews.com' 'utopia.de' 'nevalleytimes.com'
 'northcolumbusnews.com' 'rightwingwatch.org' 'theguardian.com'
 'merrimackvalleynews.com' 'natchezdemocrat.com' 'keystonenewsroom.com'
 'highline.huffingtonpost.com' 'capitalbnews.org' 'freebeacon.com'
 'twitchy.com' 'toddstarnes.com' 'intellectualtakeout.org' 'koinesune.com'
 'kyivindependent.com' 'amnews.com' 'patriotfetch.com'
 'harlanenterprise.net' 'roanoke-chowannewsherald.com'
 'northessexnews.com' 'elizabethton.com' 'magnoliastatelive.com'
 'deneenborelli.com' 'offthepress.com' 'theweek.com'
 'thenationaltelegraph.com' 'thecharlottegazette.com' 'outkick.com'
 'drudgereport.com' 'manilabusinessdaily.com' 'swalleghenynews.com'
 'christianheadlines.com' 'southwichitanews.com' 'westindynews.com'
 'ncncnews.com' 'andalusiastarnews.com' 'setennnews.com'
 'gandernewsroom.com' 'valleytimes-news.com' 'ozy.com'
 'jacksonpurchasenews.com' 'patriotjournal.org' 'centralfloridapost.com'
 'observer.com' 'floridaparishnews.com' 'gtrtimes.com'
 'thelibertarianrepublic.com' 'southdsmnews.com' 'vicksburgpost.com'
 'yellowhammernews.com' 'libertarianinstitute.org' 'thesnaponline.com'
 'southomahatimes.com' 'theminnesotasun.com' 'northhoustonnews.com'
 'westatlantanews.com' 'readfrontier.org' 'kokomostandard.com' 'mic.com'
 'nationalinterest.org' 'westlatimes.com' 'neohiotimes.com'
 'searizonanews.com' 'huffpost.com' 'english.alaraby.co.uk'
 'eaglevalleytimes.com' 'flagandcross.com']
Train label distribution (%):
label
3    26.291822
0    25.235595
2    22.958700
1    15.672633
4     9.841250
Name: proportion, dtype: float64
Test label distribution (%):
label
2    27.012278
3    24.120055
0    24.038199
1    14.679400
4    10.150068
Name: proportion, dtype: float64

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fold 3 Epoch 1/5:   0%|                                 | 0/495 [00:00<?, ?it/s]/home/fabio.pinelli/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py:1520: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Fold 3 Epoch 1/5: 100%|██████████| 495/495 [03:29<00:00,  2.36it/s, loss=1.1937]

Epoch 1 avg loss: 0.8642

Fold 3 Epoch 2/5: 100%|██████████| 495/495 [03:29<00:00,  2.36it/s, loss=1.3340]

Epoch 2 avg loss: 0.5220

Fold 3 Epoch 3/5: 100%|██████████| 495/495 [03:29<00:00,  2.36it/s, loss=0.8801]

Epoch 3 avg loss: 0.3346

Fold 3 Epoch 4/5: 100%|██████████| 495/495 [03:29<00:00,  2.36it/s, loss=0.0116]

Epoch 4 avg loss: 0.1902

Fold 3 Epoch 5/5: 100%|██████████| 495/495 [03:29<00:00,  2.36it/s, loss=0.0029]

Epoch 5 avg loss: 0.1030

Evaluating Fold 3: 100%|██████████████████████| 230/230 [00:15<00:00, 14.73it/s]

Fold 3 model saved to Results/Classification/label/Models/bert_fold_3.pt
Fold 3 results saved to Results/Classification/bert.csv

========================================
Processing BERT Fold 4/5
========================================
Train Domains: ['nemontananews.com' 'theguardiansofdemocracy.com' 'tribunemag.co.uk'
 'ecoklahomanews.com' 'valiantnews.com' 'infacts.org'
 'westhamiltonnews.com' 'patriotsgazette.com' 'salisburypost.com'
 'riverfronttimes.com' 'themadisonrecord.com' 'politico.eu'
 'ncindiananews.com' 'aei.org' 'texastribune.org' 'nationalmemo.com'
 'defenseone.com' 'eciowanews.com' 'thecoastlandtimes.com'
 'clantonadvertiser.com' 'dcenquirer.com' 'thedcpatriot.com'
 'indo-caribbean.com' 'state-journal.com' 'spiked-online.com' 'ntd.com'
 'conservtribune.com' 'dailysoundandfury.com' 'brewtonstandard.com'
 'unioncountyreview.com' 'swmontanatimes.com' 'muslimnews.co.uk'
 'christianpost.com' 'providencereporter.com' 'tennesseestar.com'
 'cbn.com' 'thejc.com' 'nwmontananews.com'
 'conservativeundergroundnews.com' 'townhall.com' '5pillarsuk.com'
 'larimernews.com' 'faithwire.com' 'litchfieldhillstoday.com'
 'clarkcountytoday.com' 'americustimesrecorder.com'
 'thepoliticalinsider.com' 'washingtonmonthly.com' 'thecountersignal.com'
 'unmuzzlednews.com' 'easterneye.biz' 'pravda.com.ua' 'hongkongfp.com'
 'americanwirenews.com' 'pressprogress.ca' 'tuscarawasnews.com'
 'norcalrecord.com' 'armaghi.com' 'nwkansasnews.com'
 'editorial.huffingtonpost.com' 'reason.com' 'waterfordtoday.com'
 'hartselleenquirer.com' 'floridapolitics.com' 'cfr.org'
 'northinlandnews.com' 'cordeledispatch.com' 'middleeasteye.net'
 'westlucasnews.com' 'claiborneprogress.net' 'truthout.org'
 'counterpunch.org' 'wcminnesotanews.com' 'politicaljournalreview.com'
 'entertainme.whatfinger.com' 'greenvilleadvocate.com'
 'grandrapidsreporter.com' 'projectveritas.com' 'utopia.de' 'linkiesta.it'
 'msmagazine.com' 'thelily.com' 'nevalleytimes.com' 'freespeech.org'
 'northcolumbusnews.com' 'mikehuckabee.com' 'theblaze.com'
 'foramerica.org' 'theroot.com' 'ourpatriot.com' 'thepostsearchlight.com'
 'rochesterreporter.com' 'theohiostar.com' 'kenbridgevictoriadispatch.com'
 'deadstate.org' 'swwyomingnews.com' 'rightwingwatch.org'
 'theguardian.com' 'merrimackvalleynews.com' 'desantisdaily.com'
 'natchezdemocrat.com' 'policetribune.com' 'northpinellasnews.com'
 'keystonenewsroom.com' 'shondaland.com' 'highline.huffingtonpost.com'
 'msnbc.com' 'dailyleader.com' 'capitalbnews.org' 'patriotpost.com'
 'freebeacon.com' 'rollcall.com' 'segeorgianews.com' 'twitchy.com'
 'rabble.ca' 'sowisconsintimes.com' 'newjerseyglobe.com'
 'aroostooknews.com' 'toddstarnes.com' 'spotlightpa.org'
 'savannahstandard.com' 'intellectualtakeout.org' 'koinesune.com'
 'alternet.org' 'mrctv.org' 'kyivindependent.com' 'cornishstuff.com'
 'theamericanonews.com' 'amnews.com' 'labourlist.org'
 'southtidewaternews.com' 'objectivist.co' 'troymessenger.com'
 'huffingtonpost.com' 'rowannews.com' 'vadogwood.com'
 'thebipartisanpress.com' 'swr3.de' 'pensacolatimes.com' 'thesun.co.uk'
 'southbrowardnews.com' 'patriotfetch.com' 'harlanenterprise.net'
 'aapsonline.org' 'politicalflare.com' 'centennialstatenews.com'
 'cardinalpine.com' 'thefirsttv.com' 'treasurevalleytimes.com'
 'queenseagle.com' 'frontpagemag.com' 'roanoke-chowannewsherald.com'
 'ukdefencejournal.org.uk' 'northessexnews.com' 'prageru.com'
 'politics.co.uk' 'dailysignal.com' 'mercertimes.com' 'elizabethton.com'
 'asiansunday.co.uk' 'jta.org' 'nigerianwatch.com' 'magnoliastatelive.com'
 'hotair.com' 'centrallouisiananews.com' 'deneenborelli.com'
 'news.sky.com' 'smithfieldtimes.com' 'justsecurity.org'
 'williamsonnews.com' 'dailyboulder.com' 'redstatewatcher.com'
 'offthepress.com' 'theweek.com' 'thenationaltelegraph.com' 'nysun.com'
 'boisecitywire.com' 'ansamed.info' 'sacorridornews.com'
 'rightnewswire.com' 'panews.com' 'westvolusianews.com'
 'thecharlottegazette.com' 'txrealtynews.com' 'outkick.com'
 'treasurecoastsun.com' 'senebraskanews.com' 'conservativewoman.co.uk'
 'drudgereport.com' 'westernjournalism.com' 'cistranfinance.com'
 'disrn.com' 'leaderpub.com' 'manilabusinessdaily.com' 'atmoreadvance.com'
 'orlandostandard.com' 'suffolknewsherald.com' 'utahvalleytimes.com'
 'thepatriotjournal.com' 'justthenews.com' 'swalleghenynews.com'
 'checksandbalancesproject.org' 'mediarightnews.com'
 'northkentuckynews.com' 'eastindynews.com' 'christianheadlines.com'
 'winchestersun.com' 'analyzingamerica.org' 'southwichitanews.com'
 'mustreadalaska.com' 'jewishpress.com' 'westindynews.com'
 'judicialwatch.org' 'ncncnews.com' 'redstate.com' 'irontontribune.com'
 'thepostmillennial.com' 'northrichmondtoday.com' 'andalusiastarnews.com'
 'independentchronicle.com' 'americanlookout.com' 'ourdavie.com'
 'selmatimesjournal.com' 'democratica.com' 'demopolistimes.com'
 'tryondailybulletin.com' 'heartlandsignal.com' 'thenevadaglobe.com'
 'centralcoloradonews.com' 'endtimeheadlines.org'
 'northbirminghamtimes.com' 'patriotpost.us' 'talkingpointsmemo.com'
 'swtennnews.com' 'thewashingtondailynews.com' 'setennnews.com'
 'gandernewsroom.com' 'sarahpalin.com' 'southkingnews.com'
 'southknoxnews.com' 'valleytimes-news.com' 'ozy.com'
 'jacksonpurchasenews.com' 'prentissheadlight.com' 'patriotjournal.org'
 'metrolexnews.com' 'gopdailybrief.com' 'newsbusters.org'
 'weststarknews.com' 'centralfloridapost.com' 'albertleatribune.com'
 'angolabusinessdaily.com' 'projectveritasaction.com'
 'eastmichigannews.com' 'polinews.org' 'dailywire.com' 'observer.com'
 'floridaparishnews.com' 'pantsonfirenews.com' 'legalinsurrection.com'
 'dallasobserver.com' 'lehightimes.com' 'gtrtimes.com'
 'shelbycountyreporter.com' 'northguilfordnews.com' 'upnorthnewswi.com'
 'lbc.co.uk' 'sturgiscoldwaternews.com' 'redrightdaily.com'
 'southcotimes.com' 'patriotpulse.net' 'ecnorthcarolinanews.com'
 'neatlantanews.com' 'thelibertarianrepublic.com'
 'conservativetribune.com' 'southdsmnews.com' 'vicksburgpost.com'
 'yellowhammernews.com' 'alabamanow.com' 'libertarianinstitute.org'
 'aldianews.com' 'deeside.com' 'thesnaponline.com' 'nickadamsusa.com'
 'cityam.com' 'southomahatimes.com' 'neonnettle.com' 'muskegonsun.com'
 'theminnesotasun.com' 'cobbreporter.com' 'renewedright.com' 'cheddar.com'
 'waterlootimes.com' 'cantonreporter.com' 'live.huffingtonpost.com'
 'henricotimes.com' 'algemeiner.com' 'easthudvalleynews.com'
 'thewildcard.com' 'greenvillereporter.com' 'patientdaily.com' 'meduza.io'
 'imperialcanews.com' 'northhoustonnews.com' 'ecmissnews.com'
 'dallasvoice.com' 'tnc.news' 'topekasun.com' 'stlouisreporter.com'
 'westatlantanews.com' 'readfrontier.org' 'olddominionnews.com'
 'northfairfaxnews.com' 'emeraldcoasttimes.com' 'westernjournal.com'
 'kokomostandard.com' 'southtrianglenews.com' 'dailypatriotreport.com'
 'mic.com' 'southatlantanews.com' 'nationalinterest.org' 'westsgvnews.com'
 'southlouisiananews.com' 'data.huffingtonpost.com' 'westlatimes.com'
 'intpolicydigest.org' 'neohiotimes.com' 'fee.org' 'southsoundtimes.com'
 'gbnews.uk' 'lewistontimes.com' 'jeffcitynews.com' 'euromaidanpress.com'
 'fayettevilletoday.com' 'luzernetimes.com'
 'thenewcivilrightsmovement.com' 'searizonanews.com' 'huffpost.com'
 'knoxtimes.com' 'english.alaraby.co.uk' 'southsfbaynews.com'
 'sandovalnews.com' 'eaglevalleytimes.com' 'petroplexnews.com' 'aclu.org'
 'americanprogress.org' 'bizpacreview.com' 'flagandcross.com'
 'politicshome.com' 'thegrayzone.com' 'truthdig.com']
Test Domains: ['middlesborodailynews.com' 'realclearinvestigations.com'
 'bluestatebluesnews.com' 'anthonyblogan.com'
 'arizonadailyindependent.com' 'southtulsatoday.com' 'indystandard.com'
 'southwinstonsalemnews.com' 'gatewayreporter.com'
 'africanvoiceonline.co.uk' 'foreignpolicy.com' 'taz.de' 'arabnews.com'
 'sfbayview.com' 'theamericanconservative.com' 'ijr.org'
 'foothillsreview.com' 'coppercourier.com' 'irishcentral.com'
 'lobservateur.com' 'illinoispolicy.org' 'politicalanimalnews.com'
 'ijr.com' 'lagrangenews.com' 'ammoland.com' 'franklincountytimes.com'
 'northcharlottetoday.com' 'georgiastarnews.com' 'oxfordeagle.com'
 'newser.com' 'sandhillstoday.com' 'brexitnews.tv' 'northhamptonnews.com'
 'lowndessignal.com' 'reitschuster.de' 'morrisleader.com'
 'theinteriorjournal.com' 'swissinfo.ch' 'netarrantnews.com'
 'steadfastdaily.com' 'elections.huffingtonpost.com' 'nachdenkseiten.de'
 'picayuneitem.com' 'thelondoneconomic.com' 'bylinetimes.com'
 'southcolumbusnews.com' 'hindstoday.com' 'projects.huffingtonpost.com'
 'themichiganstar.com' 'clemmonscourier.net' 'grabien.com'
 'seindiananews.com' 'rewirenewsgroup.com' 'notthebee.com'
 'creativedestructionmedia.com' 'respectnh.com' 'decisiondeskhq.com'
 'orangeleader.com' 'northcoastalnews.com' 'euronews.com'
 'jessaminejournal.com' 'farmvilleherald.com' 'motherjones.com'
 'amgreatness.com' 'bogalusadailynews.com' 'ntd.tv' 'w-j.co'
 'northshorelanews.com' 'kentcotimes.com' 'americanpress.com'
 'hudsontoday.com' 'evergreenreporter.com' 'educationdailywire.com'
 'thecanary.co' 'lifezette.com' 'swriversidenews.com' 'lubbocktimes.com'
 'southsidevanews.com' 'centralmissourinews.com' 'stjoebentonharbor.com'
 'cnnespanol.cnn.com' 'currentaffairs.org' 'rocklandreporter.com'
 'asianimage.co.uk' 'thefulcrum.us' 'ndnorthnews.com' 'news-front.info'
 'realrawnews.com']
Train label distribution (%):
label
3    26.409534
2    24.532291
0    24.211943
1    15.427986
4     9.418247
Name: proportion, dtype: float64
Test label distribution (%):
label
0    28.231644
3    23.759049
2    20.449845
1    15.718718
4    11.840745
Name: proportion, dtype: float64

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fold 4 Epoch 1/5:   0%|                                 | 0/488 [00:00<?, ?it/s]/home/fabio.pinelli/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py:1520: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Fold 4 Epoch 1/5: 100%|██████████| 488/488 [03:26<00:00,  2.36it/s, loss=0.5169]

Epoch 1 avg loss: 0.8717

Fold 4 Epoch 2/5: 100%|██████████| 488/488 [03:27<00:00,  2.36it/s, loss=0.5128]

Epoch 2 avg loss: 0.5398

Fold 4 Epoch 3/5: 100%|██████████| 488/488 [03:26<00:00,  2.36it/s, loss=0.2288]

Epoch 3 avg loss: 0.3506

Fold 4 Epoch 4/5: 100%|██████████| 488/488 [03:26<00:00,  2.36it/s, loss=0.1221]

Epoch 4 avg loss: 0.2111

Fold 4 Epoch 5/5: 100%|██████████| 488/488 [03:26<00:00,  2.36it/s, loss=0.0289]

Epoch 5 avg loss: 0.1154

Evaluating Fold 4: 100%|██████████████████████| 242/242 [00:16<00:00, 14.72it/s]

Fold 4 model saved to Results/Classification/label/Models/bert_fold_4.pt
Fold 4 results saved to Results/Classification/bert.csv

========================================
Processing BERT Fold 5/5
========================================
Train Domains: ['middlesborodailynews.com' 'ecoklahomanews.com'
 'realclearinvestigations.com' 'infacts.org' 'westhamiltonnews.com'
 'patriotsgazette.com' 'salisburypost.com' 'bluestatebluesnews.com'
 'themadisonrecord.com' 'politico.eu' 'ncindiananews.com'
 'anthonyblogan.com' 'arizonadailyindependent.com' 'aei.org'
 'texastribune.org' 'southtulsatoday.com' 'nationalmemo.com'
 'indystandard.com' 'eciowanews.com' 'southwinstonsalemnews.com'
 'dcenquirer.com' 'thedcpatriot.com' 'indo-caribbean.com'
 'state-journal.com' 'spiked-online.com' 'gatewayreporter.com' 'ntd.com'
 'africanvoiceonline.co.uk' 'foreignpolicy.com' 'taz.de'
 'unioncountyreview.com' 'arabnews.com' 'sfbayview.com'
 'swmontanatimes.com' 'theamericanconservative.com' 'ijr.org'
 'muslimnews.co.uk' 'foothillsreview.com' 'coppercourier.com'
 'christianpost.com' 'providencereporter.com' 'tennesseestar.com'
 'irishcentral.com' 'lobservateur.com' 'townhall.com' 'larimernews.com'
 'faithwire.com' 'litchfieldhillstoday.com' 'thepoliticalinsider.com'
 'thecountersignal.com' 'unmuzzlednews.com' 'easterneye.biz'
 'pravda.com.ua' 'hongkongfp.com' 'americanwirenews.com'
 'illinoispolicy.org' 'pressprogress.ca' 'tuscarawasnews.com'
 'politicalanimalnews.com' 'norcalrecord.com' 'armaghi.com' 'ijr.com'
 'nwkansasnews.com' 'lagrangenews.com' 'editorial.huffingtonpost.com'
 'reason.com' 'waterfordtoday.com' 'hartselleenquirer.com'
 'floridapolitics.com' 'northinlandnews.com' 'cordeledispatch.com'
 'middleeasteye.net' 'westlucasnews.com' 'truthout.org' 'counterpunch.org'
 'politicaljournalreview.com' 'entertainme.whatfinger.com'
 'greenvilleadvocate.com' 'ammoland.com' 'grandrapidsreporter.com'
 'projectveritas.com' 'franklincountytimes.com' 'northcharlottetoday.com'
 'georgiastarnews.com' 'oxfordeagle.com' 'newser.com' 'utopia.de'
 'sandhillstoday.com' 'linkiesta.it' 'msmagazine.com' 'thelily.com'
 'nevalleytimes.com' 'freespeech.org' 'northcolumbusnews.com'
 'mikehuckabee.com' 'theblaze.com' 'brexitnews.tv' 'foramerica.org'
 'theroot.com' 'ourpatriot.com' 'thepostsearchlight.com' 'theohiostar.com'
 'kenbridgevictoriadispatch.com' 'deadstate.org' 'northhamptonnews.com'
 'lowndessignal.com' 'reitschuster.de' 'rightwingwatch.org'
 'theguardian.com' 'merrimackvalleynews.com' 'desantisdaily.com'
 'natchezdemocrat.com' 'policetribune.com' 'keystonenewsroom.com'
 'shondaland.com' 'highline.huffingtonpost.com' 'morrisleader.com'
 'msnbc.com' 'capitalbnews.org' 'patriotpost.com' 'theinteriorjournal.com'
 'freebeacon.com' 'rollcall.com' 'segeorgianews.com' 'swissinfo.ch'
 'netarrantnews.com' 'twitchy.com' 'rabble.ca' 'sowisconsintimes.com'
 'newjerseyglobe.com' 'aroostooknews.com' 'steadfastdaily.com'
 'toddstarnes.com' 'elections.huffingtonpost.com' 'spotlightpa.org'
 'savannahstandard.com' 'intellectualtakeout.org' 'nachdenkseiten.de'
 'picayuneitem.com' 'koinesune.com' 'kyivindependent.com'
 'cornishstuff.com' 'theamericanonews.com' 'amnews.com' 'labourlist.org'
 'troymessenger.com' 'huffingtonpost.com' 'rowannews.com'
 'pensacolatimes.com' 'thesun.co.uk' 'southbrowardnews.com'
 'patriotfetch.com' 'harlanenterprise.net' 'aapsonline.org'
 'thelondoneconomic.com' 'centennialstatenews.com' 'cardinalpine.com'
 'thefirsttv.com' 'queenseagle.com' 'frontpagemag.com'
 'roanoke-chowannewsherald.com' 'bylinetimes.com'
 'ukdefencejournal.org.uk' 'northessexnews.com' 'politics.co.uk'
 'mercertimes.com' 'elizabethton.com' 'jta.org' 'southcolumbusnews.com'
 'nigerianwatch.com' 'magnoliastatelive.com' 'hotair.com'
 'centrallouisiananews.com' 'deneenborelli.com' 'hindstoday.com'
 'smithfieldtimes.com' 'justsecurity.org' 'dailyboulder.com'
 'offthepress.com' 'theweek.com' 'thenationaltelegraph.com'
 'projects.huffingtonpost.com' 'boisecitywire.com' 'themichiganstar.com'
 'ansamed.info' 'sacorridornews.com' 'rightnewswire.com' 'panews.com'
 'westvolusianews.com' 'thecharlottegazette.com' 'outkick.com'
 'treasurecoastsun.com' 'clemmonscourier.net' 'conservativewoman.co.uk'
 'drudgereport.com' 'westernjournalism.com' 'cistranfinance.com'
 'disrn.com' 'leaderpub.com' 'manilabusinessdaily.com'
 'suffolknewsherald.com' 'grabien.com' 'seindiananews.com'
 'thepatriotjournal.com' 'swalleghenynews.com'
 'checksandbalancesproject.org' 'northkentuckynews.com'
 'rewirenewsgroup.com' 'eastindynews.com' 'christianheadlines.com'
 'winchestersun.com' 'analyzingamerica.org' 'southwichitanews.com'
 'mustreadalaska.com' 'notthebee.com' 'westindynews.com'
 'judicialwatch.org' 'ncncnews.com' 'redstate.com' 'irontontribune.com'
 'thepostmillennial.com' 'andalusiastarnews.com' 'americanlookout.com'
 'ourdavie.com' 'creativedestructionmedia.com' 'respectnh.com'
 'selmatimesjournal.com' 'democratica.com' 'tryondailybulletin.com'
 'thenevadaglobe.com' 'endtimeheadlines.org' 'decisiondeskhq.com'
 'talkingpointsmemo.com' 'swtennnews.com' 'thewashingtondailynews.com'
 'setennnews.com' 'orangeleader.com' 'northcoastalnews.com'
 'gandernewsroom.com' 'sarahpalin.com' 'southknoxnews.com' 'euronews.com'
 'valleytimes-news.com' 'ozy.com' 'jacksonpurchasenews.com'
 'patriotjournal.org' 'jessaminejournal.com' 'metrolexnews.com'
 'gopdailybrief.com' 'weststarknews.com' 'centralfloridapost.com'
 'albertleatribune.com' 'angolabusinessdaily.com'
 'projectveritasaction.com' 'farmvilleherald.com' 'motherjones.com'
 'eastmichigannews.com' 'polinews.org' 'dailywire.com' 'observer.com'
 'floridaparishnews.com' 'legalinsurrection.com' 'lehightimes.com'
 'gtrtimes.com' 'amgreatness.com' 'bogalusadailynews.com' 'lbc.co.uk'
 'redrightdaily.com' 'southcotimes.com' 'ecnorthcarolinanews.com' 'ntd.tv'
 'w-j.co' 'thelibertarianrepublic.com' 'conservativetribune.com'
 'southdsmnews.com' 'vicksburgpost.com' 'yellowhammernews.com'
 'northshorelanews.com' 'alabamanow.com' 'kentcotimes.com'
 'libertarianinstitute.org' 'aldianews.com' 'deeside.com'
 'thesnaponline.com' 'nickadamsusa.com' 'americanpress.com'
 'southomahatimes.com' 'neonnettle.com' 'muskegonsun.com'
 'theminnesotasun.com' 'cobbreporter.com' 'cantonreporter.com'
 'live.huffingtonpost.com' 'henricotimes.com' 'algemeiner.com'
 'thewildcard.com' 'greenvillereporter.com' 'patientdaily.com' 'meduza.io'
 'imperialcanews.com' 'northhoustonnews.com' 'dallasvoice.com'
 'hudsontoday.com' 'evergreenreporter.com' 'stlouisreporter.com'
 'westatlantanews.com' 'readfrontier.org' 'olddominionnews.com'
 'northfairfaxnews.com' 'educationdailywire.com' 'emeraldcoasttimes.com'
 'thecanary.co' 'lifezette.com' 'kokomostandard.com'
 'southtrianglenews.com' 'dailypatriotreport.com' 'mic.com'
 'swriversidenews.com' 'nationalinterest.org' 'lubbocktimes.com'
 'westsgvnews.com' 'southlouisiananews.com' 'data.huffingtonpost.com'
 'westlatimes.com' 'intpolicydigest.org' 'southsidevanews.com'
 'centralmissourinews.com' 'neohiotimes.com' 'fee.org' 'gbnews.uk'
 'stjoebentonharbor.com' 'cnnespanol.cnn.com' 'currentaffairs.org'
 'rocklandreporter.com' 'euromaidanpress.com' 'fayettevilletoday.com'
 'asianimage.co.uk' 'thenewcivilrightsmovement.com' 'thefulcrum.us'
 'ndnorthnews.com' 'searizonanews.com' 'huffpost.com' 'knoxtimes.com'
 'english.alaraby.co.uk' 'southsfbaynews.com' 'eaglevalleytimes.com'
 'petroplexnews.com' 'aclu.org' 'news-front.info' 'flagandcross.com'
 'realrawnews.com' 'thegrayzone.com']
Test Domains: ['nemontananews.com' 'theguardiansofdemocracy.com' 'tribunemag.co.uk'
 'valiantnews.com' 'riverfronttimes.com' 'defenseone.com'
 'thecoastlandtimes.com' 'clantonadvertiser.com' 'conservtribune.com'
 'dailysoundandfury.com' 'brewtonstandard.com' 'cbn.com' 'thejc.com'
 'nwmontananews.com' 'conservativeundergroundnews.com' '5pillarsuk.com'
 'clarkcountytoday.com' 'americustimesrecorder.com'
 'washingtonmonthly.com' 'cfr.org' 'claiborneprogress.net'
 'wcminnesotanews.com' 'rochesterreporter.com' 'swwyomingnews.com'
 'northpinellasnews.com' 'dailyleader.com' 'alternet.org' 'mrctv.org'
 'southtidewaternews.com' 'objectivist.co' 'vadogwood.com'
 'thebipartisanpress.com' 'swr3.de' 'politicalflare.com'
 'treasurevalleytimes.com' 'prageru.com' 'dailysignal.com'
 'asiansunday.co.uk' 'news.sky.com' 'williamsonnews.com'
 'redstatewatcher.com' 'nysun.com' 'txrealtynews.com' 'senebraskanews.com'
 'atmoreadvance.com' 'orlandostandard.com' 'utahvalleytimes.com'
 'justthenews.com' 'mediarightnews.com' 'jewishpress.com'
 'northrichmondtoday.com' 'independentchronicle.com' 'demopolistimes.com'
 'heartlandsignal.com' 'centralcoloradonews.com'
 'northbirminghamtimes.com' 'patriotpost.us' 'southkingnews.com'
 'prentissheadlight.com' 'newsbusters.org' 'pantsonfirenews.com'
 'dallasobserver.com' 'shelbycountyreporter.com' 'northguilfordnews.com'
 'upnorthnewswi.com' 'sturgiscoldwaternews.com' 'patriotpulse.net'
 'neatlantanews.com' 'cityam.com' 'renewedright.com' 'cheddar.com'
 'waterlootimes.com' 'easthudvalleynews.com' 'ecmissnews.com' 'tnc.news'
 'topekasun.com' 'westernjournal.com' 'southatlantanews.com'
 'southsoundtimes.com' 'lewistontimes.com' 'jeffcitynews.com'
 'luzernetimes.com' 'sandovalnews.com' 'americanprogress.org'
 'bizpacreview.com' 'politicshome.com' 'truthdig.com']
Train label distribution (%):
label
0    25.053312
3    24.911147
2    23.922456
1    16.426494
4     9.686591
Name: proportion, dtype: float64
Test label distribution (%):
label
3    29.642589
0    24.843789
2    22.944264
1    11.847038
4    10.722319
Name: proportion, dtype: float64

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fold 5 Epoch 1/5:   0%|                                 | 0/484 [00:00<?, ?it/s]/home/fabio.pinelli/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py:1520: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)
Fold 5 Epoch 1/5:  63%|██████▎   | 305/484 [02:08<01:15,  2.36it/s, loss=0.5496]

# Memory cleanup

In [ ]:
import gc
import torch

# Manually remove large objects from previous run
llama_objects = ['model', 'tokenizer', 'train_loader', 'test_loader', 
                'train_dataset', 'test_dataset', 'train_encodings',
                'test_encodings', 'optimizer', 'scaler']

for obj in llama_objects:
    if obj in globals():
        del globals()[obj]

# Force garbage collection
gc.collect()
torch.cuda.empty_cache()

print("GPU memory cleared: {} MB".format(torch.cuda.memory_allocated() // 1024**2))

In [1]:
import pandas as pd

df = pd.read_csv('Dataset/CleannedDataset/newDataframeWithOldCleanedPoliticsVersion.csv')

df = df.reset_index(drop=True)
df

,url,title,text,authors,domain,score,country,language,topics,paywall,opinion_advocacy,label
0,https://nemontananews.com/stories/670532029-1-...,1 gas station in cities throughout Phillips Co...,Federal Energy Regulatory Commission (FERC) Ch...,Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
1,https://nemontananews.com/stories/670175501-mc...,McCone County: Income Maintenance dependency r...,"John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
2,https://nemontananews.com/stories/670489322-da...,"Daniels County residents received $13,488 per ...","John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
3,https://nemontananews.com/stories/670175454-da...,Daniels County: Income Maintenance made up 0.8...,"John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
4,https://nemontananews.com/stories/670413125-wh...,Where could drivers find the cheapest gas in c...,Federal Energy Regulatory Commission (FERC) Co...,Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19471,https://www.truthdig.com/articles/us-house-vot...,US House Vote Rolls Back Wetlands Regulations,The U.S. House voted Thursday to undo a Biden ...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19472,https://www.truthdig.com/articles/environmenta...,Environmental Racism in Canada,Informed nine months after the fact that its h...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19473,https://www.truthdig.com/articles/the-runaway-...,The Runaway Train of Corporate Greed,Thursday’s U.S. Senate hearing about the ongoi...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19474,https://www.truthdig.com/articles/ron-desantis...,Ron DeSantis’ Phantom War Against Voter Fraud,A new Florida law gives Gov.Ron DeSantis’ pros...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19475,https://www.truthdig.com/articles/the-conserva...,The Conservative Teneo Network Is Reshaping Am...,This story was originally published by ProPubl...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3

# LLAMA3

In [ ]:
import random
import gc
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)
from tqdm import tqdm
import numpy as np
import pandas as pd
import torch
import os
from torch.utils.data import DataLoader, TensorDataset
from transformers import (
    BitsAndBytesConfig,
    AutoTokenizer,
    AutoModelForSequenceClassification,
    get_scheduler,
)
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model
import bitsandbytes as bnb
from torch.optim import AdamW


# Set random seed
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(RANDOM_SEED)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def run_llama_finetuning_domain_stratified_cv(
    df,
    label_col,
    text_col,
    output_csv_path,
    domain_col=None,
    num_epochs=5,
    train_batch_size=32,
    eval_batch_size=64,
    gradient_accumulation_steps=2,
    max_seq_length=256,
    n_splits=5,
    model_id="meta-llama/Meta-Llama-3-8B",
    device=None,
    val_size=0.1,
    early_stopping_patience=2,
):
    """
    Improved fine-tuning flow with:
      - longer sequence length (default 256)
      - extended LoRA target modules
      - gradient checkpointing
      - per-fold train/val split and early stopping (based on val loss)
      - class-weighted loss to handle imbalance
      - LR scheduler (linear warmup + cosine decay)
      - dynamic eval batch fallback on OOM
      - proper model reinitialization per fold for correct CV
      - [NEW] Logs train and val loss per epoch to the output CSV.

    Note: this is still a memory-heavy recipe; adjust batch sizes or switch to smaller model if GPU OOM.
    """

    # --- Configuration & device ---
    DEVICE = device or (torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu"))
    MODEL_ID = model_id
    NUM_EPOCHS = num_epochs
    TRAIN_BATCH_SIZE = train_batch_size
    EVAL_BATCH_SIZE = eval_batch_size
    GRADIENT_ACCUMULATION_STEPS = gradient_accumulation_steps
    MAX_SEQ_LENGTH = max_seq_length
    N_SPLITS = n_splits

    # --- Data and Label Processing ---
    df = df.copy().reset_index(drop=True)

    unique_labels = sorted(df[label_col].unique())
    num_labels = len(unique_labels)
    print(f"Detected {num_labels} unique labels: {unique_labels}")
    label_mapping = {label: i for i, label in enumerate(unique_labels)}
    df["mapped_label"] = df[label_col].map(label_mapping)
    print(f"Mapped labels: {label_mapping}")

    # --- Tokenizer (initialized once) ---
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    # ensure pad token
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # --- Quantization Config (reused for each fold) ---
    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
    )

    # --- LoRA configuration (reused for each fold) ---
    lora_config = LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "down_proj",
            "up_proj",
        ],
        lora_dropout=0.05,
        bias="none",
        task_type="SEQ_CLS",
    )

    # --- Cross-Validation Folds ---
    if domain_col and domain_col in df.columns:
        print(f"Using domain-level stratification on column '{domain_col}'...")
        grouped = df.groupby(domain_col)
        domains = list(grouped.groups.keys())
        stratify_labels = [group[1]["mapped_label"].mode()[0] for group in grouped]
        skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_SEED)
        folds = []
        for train_idx, test_idx in skf.split(domains, stratify_labels):
            train_domains = [domains[i] for i in train_idx]
            test_domains = [domains[i] for i in test_idx]
            train_df = df[df[domain_col].isin(train_domains)].reset_index(drop=True)
            test_df = df[df[domain_col].isin(test_domains)].reset_index(drop=True)
            folds.append((train_df, test_df))
    else:
        print("Using standard stratified splitting...")
        skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_SEED)
        folds = [(df.iloc[train_idx].reset_index(drop=True), df.iloc[test_idx].reset_index(drop=True))
                 for train_idx, test_idx in skf.split(df, df["mapped_label"])]

    all_fold_results = []
    all_fold_preds = []

    # --- Training and Evaluation per fold ---
    for fold_idx, (train_df, test_df) in enumerate(folds):
        print(f"\n{'='*40}")
        print(f"Processing Fold {fold_idx+1}/{N_SPLITS}")
        print(f"{'='*40}")

        # split train into train/val for early stopping
        if len(train_df) > 1:
            stratify = train_df["mapped_label"] if len(train_df["mapped_label"].unique()) > 1 else None
            train_part, val_part = train_test_split(
                train_df,
                test_size=val_size,
                random_state=RANDOM_SEED,
                stratify=stratify,
            )
        else:
            train_part = train_df
            val_part = test_df.sample(frac=min(0.1, 1.0), random_state=RANDOM_SEED)

        # --- Tokenization ---
        train_encodings = tokenizer(
            train_part[text_col].tolist(),
            truncation=True,
            padding=True,
            max_length=MAX_SEQ_LENGTH,
            return_tensors="pt",
        )
        val_encodings = tokenizer(
            val_part[text_col].tolist(),
            truncation=True,
            padding=True,
            max_length=MAX_SEQ_LENGTH,
            return_tensors="pt",
        )
        test_encodings = tokenizer(
            test_df[text_col].tolist(),
            truncation=True,
            padding=True,
            max_length=MAX_SEQ_LENGTH,
            return_tensors="pt",
        )

        train_dataset = TensorDataset(
            train_encodings.input_ids,
            train_encodings.attention_mask,
            torch.tensor(train_part["mapped_label"].tolist()),
        )
        val_dataset = TensorDataset(
            val_encodings.input_ids,
            val_encodings.attention_mask,
            torch.tensor(val_part["mapped_label"].tolist()),
        )
        test_dataset = TensorDataset(
            test_encodings.input_ids,
            test_encodings.attention_mask,
            torch.tensor(test_df["mapped_label"].tolist()),
        )

        train_loader = DataLoader(
            train_dataset,
            batch_size=TRAIN_BATCH_SIZE,
            shuffle=True,
            num_workers=2,
            pin_memory=True,
        )

        # --- CREATE FRESH MODEL FOR EACH FOLD ---
        print(f"Initializing fresh model for fold {fold_idx+1}...")
        base_model = AutoModelForSequenceClassification.from_pretrained(
            MODEL_ID,
            quantization_config=quantization_config,
            num_labels=num_labels,
            device_map="auto",
        )
        base_model.config.pad_token_id = tokenizer.eos_token_id

        model = prepare_model_for_kbit_training(base_model)
        model = get_peft_model(model, lora_config)
        model.to(DEVICE)

        # enable gradient checkpointing to reduce memory at cost of compute
        try:
            model.gradient_checkpointing_enable()
        except Exception:
            pass

        # compute class weights for imbalanced data
        class_counts = train_part["mapped_label"].value_counts().sort_index()
        weights = 1.0 / (class_counts.values + 1e-12)
        weights = weights / weights.sum()
        class_weights = torch.tensor(weights, dtype=torch.float).to(DEVICE)
        criterion = torch.nn.CrossEntropyLoss(weight=class_weights)

        # optimizer (8-bit Adam from bitsandbytes) — keep params in 8bit for memory
        try:
            optimizer = bnb.optim.AdamW8bit(model.parameters(), lr=2e-5)
        except Exception:
            optimizer = AdamW(model.parameters(), lr=2e-5)

        # scheduler: linear warmup + cosine decay
        num_update_steps_per_epoch = max(1, len(train_loader) // GRADIENT_ACCUMULATION_STEPS)
        max_train_steps = NUM_EPOCHS * num_update_steps_per_epoch
        num_warmup_steps = int(0.06 * max_train_steps)
        scheduler = get_scheduler(
            name="cosine",
            optimizer=optimizer,
            num_warmup_steps=num_warmup_steps,
            num_training_steps=max_train_steps,
        )

        scaler = torch.cuda.amp.GradScaler() if torch.cuda.is_available() else None

        best_val_loss = float("inf")
        epochs_without_improve = 0
        best_model_state = None
        
        # <--- MODIFICA 1: Inizializza le liste per le loss del fold ---
        fold_train_losses = []
        fold_val_losses = []

        # --- Training ---
        for epoch in range(NUM_EPOCHS):
            model.train()
            total_loss = 0.0
            optimizer.zero_grad()
            pbar = tqdm(train_loader, desc=f"Fold {fold_idx+1} | Epoch {epoch+1}/{NUM_EPOCHS} (Training)")
            for step, batch in enumerate(pbar):
                input_ids = batch[0].to(DEVICE, non_blocking=True)
                attention_mask = batch[1].to(DEVICE, non_blocking=True)
                labels = batch[2].to(DEVICE, non_blocking=True)

                if scaler is not None:
                    with torch.cuda.amp.autocast():
                        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                        logits = outputs.logits
                        loss = criterion(logits, labels) / GRADIENT_ACCUMULATION_STEPS
                    scaler.scale(loss).backward()
                else:
                    outputs = model(input_ids=input_ids, attention_mask=attention_mask)
                    logits = outputs.logits
                    loss = criterion(logits, labels) / GRADIENT_ACCUMULATION_STEPS
                    loss.backward()

                if (step + 1) % GRADIENT_ACCUMULATION_STEPS == 0:
                    if scaler is not None:
                        scaler.step(optimizer)
                        scaler.update()
                    else:
                        optimizer.step()
                    scheduler.step()
                    optimizer.zero_grad()

                total_loss += loss.item() * GRADIENT_ACCUMULATION_STEPS
                pbar.set_postfix({"loss": total_loss / (step + 1)})
            
            pbar.close()
            # <--- MODIFICA 2a: Calcola e salva la loss media di training per l'epoca ---
            avg_train_loss = total_loss / len(train_loader) if len(train_loader) > 0 else 0.0
            fold_train_losses.append(avg_train_loss)

            # --- Validation after each epoch ---
            model.eval()
            val_losses = []
            val_preds = []
            val_trues = []
            val_loader = DataLoader(
                val_dataset,
                batch_size=EVAL_BATCH_SIZE,
                shuffle=False,
                num_workers=2,
                pin_memory=True,
            )
            with torch.no_grad():
                for batch in val_loader:
                    inputs = {
                        "input_ids": batch[0].to(DEVICE, non_blocking=True),
                        "attention_mask": batch[1].to(DEVICE, non_blocking=True),
                    }
                    labels = batch[2].to(DEVICE, non_blocking=True)
                    outputs = model(**inputs)
                    logits = outputs.logits
                    loss = criterion(logits, labels)
                    val_losses.append(loss.item())
                    preds = torch.argmax(logits, dim=1).cpu().numpy()
                    val_preds.extend(preds.tolist())
                    val_trues.extend(labels.cpu().numpy().tolist())

            mean_val_loss = float(np.mean(val_losses)) if len(val_losses) > 0 else float("inf")
            
            # <--- MODIFICA 2b: Salva la loss media di validazione per l'epoca ---
            fold_val_losses.append(mean_val_loss)
            
            # <--- MODIFICA 2c: Aggiorna il print per mostrare entrambe le loss ---
            print(f"Fold {fold_idx+1} Epoch {epoch+1} | train_loss={avg_train_loss:.4f} | val_loss={mean_val_loss:.4f}")

            # early stopping check
            if mean_val_loss < best_val_loss:
                best_val_loss = mean_val_loss
                epochs_without_improve = 0
                # save best model state in memory
                best_model_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
                print(f"New best model for fold {fold_idx+1} at epoch {epoch+1}")
            else:
                epochs_without_improve += 1
                if epochs_without_improve >= early_stopping_patience:
                    print(f"Early stopping at epoch {epoch+1} for fold {fold_idx+1}")
                    break

        # --- Load best model state for evaluation ---
        if best_model_state is not None:
            model.load_state_dict(best_model_state)
            model.to(DEVICE)
            print(f"Loaded best model state for fold {fold_idx+1}")

        # --- Evaluation on test set ---
        model.eval()
        val_preds_list = []
        val_true_labels = []

        eval_batch_size = EVAL_BATCH_SIZE
        while True:
            try:
                test_loader = DataLoader(
                    test_dataset,
                    batch_size=eval_batch_size,
                    shuffle=False,
                    num_workers=2,
                    pin_memory=True,
                )
                with torch.no_grad():
                    pbar = tqdm(test_loader, desc=f"Fold {fold_idx+1} (Evaluating)")
                    for batch in pbar:
                        inputs = {
                            "input_ids": batch[0].to(DEVICE, non_blocking=True),
                            "attention_mask": batch[1].to(DEVICE, non_blocking=True),
                        }
                        outputs = model(**inputs)
                        preds = torch.argmax(outputs.logits, dim=1).cpu().numpy()
                        val_preds_list.extend(preds.tolist())
                        val_true_labels.extend(batch[2].cpu().numpy().tolist())
                break
            except RuntimeError as e:
                if "out of memory" in str(e):
                    torch.cuda.empty_cache()
                    eval_batch_size = max(1, eval_batch_size // 2)
                    print(f"[OOM] Reducing eval batch size to {eval_batch_size} and retrying...")
                else:
                    raise

        # --- Metrics ---
        balanced_acc = balanced_accuracy_score(val_true_labels, val_preds_list)
        accuracy = accuracy_score(val_true_labels, val_preds_list)
        precision_micro = precision_score(val_true_labels, val_preds_list, average="micro", zero_division=0)
        precision_macro = precision_score(val_true_labels, val_preds_list, average="macro", zero_division=0)
        precision_weighted = precision_score(val_true_labels, val_preds_list, average="weighted", zero_division=0)
        recall_micro = recall_score(val_true_labels, val_preds_list, average="micro", zero_division=0)
        recall_macro = recall_score(val_true_labels, val_preds_list, average="macro", zero_division=0)
        recall_weighted = recall_score(val_true_labels, val_preds_list, average="weighted", zero_division=0)
        f1_micro = f1_score(val_true_labels, val_preds_list, average="micro", zero_division=0)
        f1_macro = f1_score(val_true_labels, val_preds_list, average="macro", zero_division=0)
        f1_weighted = f1_score(val_true_labels, val_preds_list, average="weighted", zero_division=0)
        confusion = confusion_matrix(val_true_labels, val_preds_list).tolist()

        # <--- MODIFICA 3: Aggiungi le liste di loss al dizionario dei risultati ---
        fold_results = {
            "Fold": fold_idx + 1,
            "Train_Losses_Per_Epoch": str(fold_train_losses),  # <--- Aggiunto
            "Val_Losses_Per_Epoch": str(fold_val_losses),      # <--- Aggiunto
            "Balanced_Accuracy": balanced_acc,
            "Accuracy": accuracy,
            "Precision_Micro": precision_micro,
            "Precision_Macro": precision_macro,
            "Precision_Weighted": precision_weighted,
            "Recall_Micro": recall_micro,
            "Recall_Macro": recall_macro,
            "Recall_Weighted": recall_weighted,
            "F1_Micro": f1_micro,
            "F1_Macro": f1_macro,
            "F1_Weighted": f1_weighted,
            "Confusion_Matrix": str(confusion),
            "Val_True_Labels": str(val_true_labels),
            "Val_Predictions": str(val_preds_list),
        }

        all_fold_results.append(fold_results)
        all_fold_preds.append(val_preds_list)

        # Save model for this fold
        model_save_dir = f"Results/Classification/{label_col}/Models"
        os.makedirs(model_save_dir, exist_ok=True)
        model_save_path = os.path.join(model_save_dir, f"llama_fold_{fold_idx+1}.pt")
        try:
            torch.save(model.state_dict(), model_save_path)
            print(f"Fold {fold_idx+1} model saved to {model_save_path}")
        except Exception as e:
            print(f"Could not save model for fold {fold_idx+1}: {e}")

        # Cleanup
        del model, optimizer, scheduler, train_loader, test_loader, val_loader
        del base_model, best_model_state
        torch.cuda.empty_cache()
        gc.collect()

        # Save results after each fold (overwrites the CSV)
        results_df = pd.DataFrame(all_fold_results)
        os.makedirs(os.path.dirname(output_csv_path), exist_ok=True)
        results_df.to_csv(output_csv_path, index=False)
        print(f"Results after fold {fold_idx+1} saved to {output_csv_path}")

    print("\nCross-validation completed. Final results saved to", output_csv_path)
    return results_df

/home/fabio.pinelli/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py:628: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2025-11-12 09:42:21.402148: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-12 09:42:21.447430: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1762940541.500786 1047220 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1762940541.519912 1047220 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1762940541.560049 1047220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1762940541.560091 1047220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1762940541.560094 1047220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1762940541.560097 1047220 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-11-12 09:42:21.575266: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [ ]:
results_df = run_llama_finetuning_domain_stratified_cv(
    df=df,
    text_col="text",
    label_col="label",
    output_csv_path="Results/Classification/llama.csv",
    domain_col="domain"
)

Detected 5 unique labels: [0, 1, 2, 3, 4]
Mapped labels: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
Using domain-level stratification on column 'domain'...

========================================
Processing Fold 1/5
========================================
Initializing fresh model for fold 1...

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Meta-Llama-3-8B and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Fold 1 | Epoch 1/5 (Training):   0%|                    | 0/439 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
Fold 1 | Epoch 1/5 (Training):  80%|▊| 353/439 [45:09<10:58,  7.66s/it, loss=2.5

# Memory cleanup

In [ ]:
import gc
import torch

# Manually remove large objects from previous run
llama_objects = ['model', 'tokenizer', 'train_loader', 'test_loader', 
                'train_dataset', 'test_dataset', 'train_encodings',
                'test_encodings', 'optimizer', 'scaler']

for obj in llama_objects:
    if obj in globals():
        del globals()[obj]

# Force garbage collection
gc.collect()
torch.cuda.empty_cache()

print("GPU memory cleared: {} MB".format(torch.cuda.memory_allocated() // 1024**2))

In [2]:
import pandas as pd

df = pd.read_csv('Dataset/CleannedDataset/newDataframeWithOldCleanedPoliticsVersion.csv')

df = df.reset_index(drop=True)
df

,url,title,text,authors,domain,score,country,language,topics,paywall,opinion_advocacy,label
0,https://nemontananews.com/stories/670532029-1-...,1 gas station in cities throughout Phillips Co...,Federal Energy Regulatory Commission (FERC) Ch...,Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
1,https://nemontananews.com/stories/670175501-mc...,McCone County: Income Maintenance dependency r...,"John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
2,https://nemontananews.com/stories/670489322-da...,"Daniels County residents received $13,488 per ...","John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
3,https://nemontananews.com/stories/670175454-da...,Daniels County: Income Maintenance made up 0.8...,"John Lettieri, President and CEO of Economic I...",Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
4,https://nemontananews.com/stories/670413125-wh...,Where could drivers find the cheapest gas in c...,Federal Energy Regulatory Commission (FERC) Co...,Northeast Montana News,nemontananews.com,32.0,US,en,Political news or commentary,No,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...
19471,https://www.truthdig.com/articles/us-house-vot...,US House Vote Rolls Back Wetlands Regulations,The U.S. House voted Thursday to undo a Biden ...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19472,https://www.truthdig.com/articles/environmenta...,Environmental Racism in Canada,Informed nine months after the fact that its h...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19473,https://www.truthdig.com/articles/the-runaway-...,The Runaway Train of Corporate Greed,Thursday’s U.S. Senate hearing about the ongoi...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19474,https://www.truthdig.com/articles/ron-desantis...,Ron DeSantis’ Phantom War Against Voter Fraud,A new Florida law gives Gov.Ron DeSantis’ pros...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3
19475,https://www.truthdig.com/articles/the-conserva...,The Conservative Teneo Network Is Reshaping Am...,This story was originally published by ProPubl...,NaN,truthdig.com,80.0,NaN,NaN,Political_news_or_commentary,NaN,NaN,3

# Roberta

In [5]:
import gc
import torch
import random
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)
from torch.utils.data import DataLoader, TensorDataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, get_linear_schedule_with_warmup
from torch.optim import AdamW
from torch.cuda.amp import autocast, GradScaler
from tqdm import tqdm
import os
import warnings
warnings.filterwarnings('ignore')


def set_deterministic_seed(seed=42):
    """
    Configura il seed in modo completamente deterministico per riproducibilità.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    
    # Importante: questi settings garantiscono determinismo ma riducono leggermente le performance
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    
    # Per trasformers
    os.environ['PYTHONHASHSEED'] = str(seed)
    os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'
    
    # PyTorch 1.8+: abilita modalità deterministica
    if hasattr(torch, 'use_deterministic_algorithms'):
        torch.use_deterministic_algorithms(True, warn_only=True)


def roberta_cross_validation_domain_stratified(
    df, 
    label_col, 
    text_col, 
    results_csv_path, 
    domain_col=None, 
    seed=42,
    batch_size=32,
    num_epochs=5,
    learning_rate=2e-5,
    max_length=256,
    gradient_accumulation_steps=1,
    use_deterministic=True
):
    """
    Performs 5-fold domain-level stratified cross-validation using RoBERTa-large.
    
    Miglioramenti principali:
    - Determinismo completo se use_deterministic=True
    - Gradient accumulation per batch effettivi più grandi
    - Ottimizzazioni memoria con chunked processing
    - Early stopping opzionale
    - Migliore gestione mixed precision
    - DataLoader più efficiente
    """
    
    # Configura determinismo
    if use_deterministic:
        set_deterministic_seed(seed)
        print(f"✓ Modalità deterministica abilitata con seed={seed}")
    else:
        # Performance mode
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
            torch.backends.cudnn.deterministic = False
            torch.backends.cudnn.benchmark = True
        print(f"✓ Modalità performance abilitata con seed={seed}")

    model_name = "roberta-large"
    df = df.reset_index(drop=True).copy()
    
    # Label mapping
    unique_labels = sorted(df[label_col].unique())
    label_map = {label: i for i, label in enumerate(unique_labels)}
    df['mapped_label'] = df[label_col].map(label_map)
    num_labels = len(unique_labels)

    print(f"\n{'='*60}")
    print(f"Label mapping: {label_map}")
    print(f"Detected {num_labels} unique labels")
    print(f"{'='*60}\n")

    # Device setup
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name(0)}")
        print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)

    # --- TOKENIZZAZIONE OTTIMIZZATA ---
    print("\n🔄 Pre-tokenizing all data...")
    
    # Tokenizza in chunks per evitare OOM su dataset grandi
    chunk_size = 1000
    all_input_ids = []
    all_attention_masks = []
    
    for i in tqdm(range(0, len(df), chunk_size), desc="Tokenizing"):
        chunk = df[text_col].iloc[i:i+chunk_size].tolist()
        encodings = tokenizer(
            chunk,
            truncation=True,
            padding="max_length",
            max_length=max_length,
            return_tensors="pt"
        )
        all_input_ids.append(encodings.input_ids)
        all_attention_masks.append(encodings.attention_mask)
    
    # Concatena tutto
    all_input_ids = torch.cat(all_input_ids, dim=0).contiguous()
    all_attention_masks = torch.cat(all_attention_masks, dim=0).contiguous()
    
    print(f"✓ Tokenization complete. Shape: {all_input_ids.shape}")
    
    # Mantieni su CPU per ora, spostiamo su GPU solo i batch necessari
    # Questo risparmia memoria GPU per dataset grandi
    all_labels = torch.tensor(df['mapped_label'].tolist(), dtype=torch.long)

    # --- DOMAIN-STRATIFIED FOLDS ---
    print("\n📊 Creating stratified folds...")
    if domain_col and domain_col in df.columns:
        grouped = df.groupby(domain_col)
        domains = list(grouped.groups.keys())
        stratify_labels = [group['mapped_label'].mode()[0] for _, group in grouped]
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
        folds = []
        for train_idx, test_idx in skf.split(domains, stratify_labels):
            train_domains = [domains[i] for i in train_idx]
            test_domains = [domains[i] for i in test_idx]
            train_indices = df[df[domain_col].isin(train_domains)].index.tolist()
            test_indices = df[df[domain_col].isin(test_domains)].index.tolist()
            folds.append((train_indices, test_indices))
        print(f"✓ Domain-stratified folds created")
    else:
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
        folds = [(train_idx.tolist(), test_idx.tolist()) 
                 for train_idx, test_idx in skf.split(df, df['mapped_label'])]
        print(f"✓ Standard stratified folds created")

    all_fold_results = []

    # --- TRAINING LOOP ---
    for fold_idx, (train_indices, test_indices) in enumerate(folds):
        print(f"\n{'='*60}")
        print(f"🚀 FOLD {fold_idx+1}/5")
        print(f"{'='*60}")

        train = df.iloc[train_indices].reset_index(drop=True)
        test = df.iloc[test_indices].reset_index(drop=True)

        if domain_col and domain_col in df.columns:
            print(f"Train Domains ({len(train[domain_col].unique())}): {sorted(train[domain_col].unique())[:5]}...")
            print(f"Test Domains ({len(test[domain_col].unique())}): {sorted(test[domain_col].unique())[:5]}...")

        print(f"\nTrain size: {len(train)} | Test size: {len(test)}")
        print("\nTrain label distribution (%):")
        print(train['mapped_label'].value_counts(normalize=True).mul(100).round(2))
        print("\nTest label distribution (%):")
        print(test['mapped_label'].value_counts(normalize=True).mul(100).round(2))

        # Cleanup
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

        # Create datasets
        train_dataset = TensorDataset(
            all_input_ids[train_indices],
            all_attention_masks[train_indices],
            all_labels[train_indices]
        )
        test_dataset = TensorDataset(
            all_input_ids[test_indices],
            all_attention_masks[test_indices],
            all_labels[test_indices]
        )

        # DataLoaders ottimizzati
        train_loader = DataLoader(
            train_dataset,
            batch_size=batch_size,
            shuffle=True,
            num_workers=2,  # Usa workers per pre-fetching
            pin_memory=True,
            prefetch_factor=2,
            persistent_workers=True,
            generator=torch.Generator().manual_seed(seed) if use_deterministic else None
        )
        test_loader = DataLoader(
            test_dataset,
            batch_size=batch_size * 2,  # Batch più grandi per inference
            shuffle=False,
            num_workers=2,
            pin_memory=True,
            prefetch_factor=2,
            persistent_workers=True
        )

        # Load model
        print("\n🔧 Loading model...")
        model = AutoModelForSequenceClassification.from_pretrained(
            model_name,
            num_labels=num_labels
        )
        
        # Gradient checkpointing per risparmiare memoria
        if hasattr(model, 'gradient_checkpointing_enable'):
            model.gradient_checkpointing_enable()
        
        model = model.to(device)

        # Optimizer con fused operations per performance
        optimizer = AdamW(
            model.parameters(),
            lr=learning_rate,
            weight_decay=0.01,
            eps=1e-8,
            fused=torch.cuda.is_available() and not use_deterministic
        )

        # Scheduler
        num_training_steps = len(train_loader) * num_epochs // gradient_accumulation_steps
        num_warmup_steps = num_training_steps // 10
        scheduler = get_linear_schedule_with_warmup(
            optimizer,
            num_warmup_steps=num_warmup_steps,
            num_training_steps=num_training_steps
        )

        # Mixed precision setup
        use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported() and not use_deterministic
        dtype = torch.bfloat16 if use_bf16 else torch.float16
        scaler = None if use_bf16 else (GradScaler() if torch.cuda.is_available() else None)

        print(f"Mixed precision: {'bfloat16' if use_bf16 else 'float16' if scaler else 'disabled'}")
        print(f"Gradient accumulation steps: {gradient_accumulation_steps}")
        print(f"Effective batch size: {batch_size * gradient_accumulation_steps}")

        # --- TRAINING ---
        print("\n🏋️ Training...")
        best_val_loss = float('inf')
        
        for epoch in range(num_epochs):
            model.train()
            train_loss = 0
            optimizer.zero_grad(set_to_none=True)
            
            progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}")
            
            for step, batch in enumerate(progress_bar):
                input_ids = batch[0].to(device, non_blocking=True)
                attention_mask = batch[1].to(device, non_blocking=True)
                labels = batch[2].to(device, non_blocking=True)

                # Mixed precision training
                if torch.cuda.is_available():
                    with autocast(dtype=dtype):
                        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                        loss = outputs.loss / gradient_accumulation_steps
                    
                    if scaler is not None:
                        scaler.scale(loss).backward()
                    else:
                        loss.backward()
                else:
                    outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
                    loss = outputs.loss / gradient_accumulation_steps
                    loss.backward()

                # Update ogni gradient_accumulation_steps
                if (step + 1) % gradient_accumulation_steps == 0:
                    if scaler is not None:
                        scaler.unscale_(optimizer)
                        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                        scaler.step(optimizer)
                        scaler.update()
                    else:
                        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                        optimizer.step()
                    
                    scheduler.step()
                    optimizer.zero_grad(set_to_none=True)

                train_loss += loss.item() * gradient_accumulation_steps
                progress_bar.set_postfix({'loss': f"{loss.item() * gradient_accumulation_steps:.4f}"})

            avg_loss = train_loss / len(train_loader)
            print(f"Epoch {epoch+1} - Avg Loss: {avg_loss:.4f}")

        # --- EVALUATION ---
        print("\n📈 Evaluating...")
        model.eval()
        val_preds, val_labels_list = [], []

        with torch.no_grad():
            for batch in tqdm(test_loader, desc="Evaluating"):
                input_ids = batch[0].to(device, non_blocking=True)
                attention_mask = batch[1].to(device, non_blocking=True)
                labels = batch[2]

                if torch.cuda.is_available():
                    with autocast(dtype=dtype):
                        outputs = model(input_ids, attention_mask=attention_mask)
                else:
                    outputs = model(input_ids, attention_mask=attention_mask)

                preds = torch.argmax(outputs.logits, dim=1)
                val_preds.extend(preds.cpu().tolist())
                val_labels_list.extend(labels.tolist())

        # Metrics
        balanced_acc = balanced_accuracy_score(val_labels_list, val_preds)
        accuracy = accuracy_score(val_labels_list, val_preds)
        precision_macro = precision_score(val_labels_list, val_preds, average="macro", zero_division=0)
        precision_weighted = precision_score(val_labels_list, val_preds, average="weighted", zero_division=0)
        recall_macro = recall_score(val_labels_list, val_preds, average="macro", zero_division=0)
        recall_weighted = recall_score(val_labels_list, val_preds, average="weighted", zero_division=0)
        f1_macro = f1_score(val_labels_list, val_preds, average="macro", zero_division=0)
        f1_weighted = f1_score(val_labels_list, val_preds, average="weighted", zero_division=0)
        confusion = confusion_matrix(val_labels_list, val_preds).tolist()

        print(f"\n📊 Results:")
        print(f"  Balanced Accuracy: {balanced_acc:.4f}")
        print(f"  Accuracy: {accuracy:.4f}")
        print(f"  F1 Macro: {f1_macro:.4f}")
        print(f"  F1 Weighted: {f1_weighted:.4f}")

        fold_results = pd.DataFrame({
            "Fold": [fold_idx + 1],
            "Balanced_Accuracy": [balanced_acc],
            "Accuracy": [accuracy],
            "Precision_Macro": [precision_macro],
            "Precision_Weighted": [precision_weighted],
            "Recall_Macro": [recall_macro],
            "Recall_Weighted": [recall_weighted],
            "F1_Macro": [f1_macro],
            "F1_Weighted": [f1_weighted],
            "Confusion_Matrix": [confusion],
            "Val_True_Labels": [val_labels_list],
            "Val_Predictions": [val_preds]
        })

        # Save model
        model_save_dir = f"Results/Classification/{label_col}/Models"
        os.makedirs(model_save_dir, exist_ok=True)
        model_save_path = os.path.join(model_save_dir, f"roberta_fold_{fold_idx+1}.pt")
        
        torch.save(model.state_dict(), model_save_path)
        print(f"💾 Model saved to {model_save_path}")

        # Save results
        try:
            existing = pd.read_csv(results_csv_path)
            results = pd.concat([existing, fold_results], ignore_index=True)
        except FileNotFoundError:
            results = fold_results

        results.to_csv(results_csv_path, index=False)
        print(f"💾 Results saved to {results_csv_path}")

        # Cleanup
        del model, optimizer, scheduler, train_loader, test_loader
        del train_dataset, test_dataset
        if scaler is not None:
            del scaler
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    # Final cleanup
    del all_input_ids, all_attention_masks, all_labels
    gc.collect()

    print(f"\n{'='*60}")
    print("✅ Cross-validation completed successfully!")
    print(f"{'='*60}\n")
    
    return results

In [ ]:
roberta_cross_validation_domain_stratified(
    df=df,
    text_col="text",
    label_col="label",
    results_csv_path="Results/Classification/roberta.csv",
    domain_col="domain",
)

✓ Modalità deterministica abilitata con seed=42

============================================================
Label mapping: {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
Detected 5 unique labels
============================================================

Using device: cuda
GPU: Tesla V100S-PCIE-32GB
GPU Memory: 34.09 GB

🔄 Pre-tokenizing all data...

Tokenizing: 100%|███████████████████████████████| 20/20 [00:18<00:00,  1.08it/s]

✓ Tokenization complete. Shape: torch.Size([19476, 256])

📊 Creating stratified folds...
✓ Domain-stratified folds created

============================================================
🚀 FOLD 1/5
============================================================
Train Domains (351): ['5pillarsuk.com', 'aei.org', 'africanvoiceonline.co.uk', 'alabamanow.com', 'albertleatribune.com']...
Test Domains (88): ['aapsonline.org', 'aclu.org', 'algemeiner.com', 'americanwirenews.com', 'analyzingamerica.org']...

Train size: 15581 | Test size: 3895

Train label distribution (%):
mapped_label
0    25.38
3    25.21
2    24.78
1    14.25
4    10.38
Name: proportion, dtype: float64

Test label distribution (%):
mapped_label
3    28.58
0    23.54
1    20.44
2    19.49
4     7.96
Name: proportion, dtype: float64

🔧 Loading model...

2025-11-14 10:16:27.122838: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-11-14 10:16:27.144570: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1763115387.168905 2339933 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1763115387.177055 2339933 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1763115387.200348 2339933 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1763115387.200398 2339933 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1763115387.200401 2339933 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1763115387.200403 2339933 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-11-14 10:16:27.208225: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Mixed precision: float16
Gradient accumulation steps: 1
Effective batch size: 32

🏋️ Training...

Epoch 1/5:   0%|                                        | 0/487 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Epoch 1/5:  23%|███▊             | 111/487 [01:01<03:31,  1.78it/s, loss=0.8436]